package gov.va.api.health.argonaut.api.resources;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/** Samples for swagger documentation. */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
class SwaggerExamples {

  static final String CONDITION =
      "{ \n"
          + "    resourceType: \"Condition\", \n"
          + "    id: \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "    patient: { \n"
          + "        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "    }, \n"
          + "    code: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                code: \"38341003\", \n"
          + "                system: \"https://www.snomed.org/snomed-ct\", \n"
          + "                display: \"Hypertension\" \n"
          + "            } \n"
          + "        ], \n"
          + "        text: \"Hypertension\" \n"
          + "    }, \n"
          + "    category: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"http://argonaut.hl7.org\", \n"
          + "                code: \"problem\" \n"
          + "            } \n"
          + "        ] \n"
          + "    }, \n"
          + "    clinicalStatus: \"active\", \n"
          + "    verificationStatus: \"unknown\", \n"
          + "    dateRecorded: \"2013-04-14\", \n"
          + "    onsetDateTime: \"2013-04-15T01:15:52Z\" \n"
          + "} ";
  static final String CONDITION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Condition\", \n"
          + "                    id: \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "                    patient: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                        coding: [ \n"
          + "                           { \n"
          + "                               code: \"38341003\", \n"
          + "                               system: \"https://www.snomed.org/snomed-ct\", \n"
          + "                               display: \"Hypertension\" \n"
          + "                           } \n"
          + "                        ], \n"
          + "                        text: \"Hypertension\" \n"
          + "                    }, \n"
          + "                    category: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://argonaut.hl7.org\", \n"
          + "                                code: \"problem\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    clinicalStatus: \"active\", \n"
          + "                    verificationStatus: \"unknown\", \n"
          + "                    dateRecorded: \"2013-04-14\", \n"
          + "                    onsetDateTime: \"2013-04-15T01:15:52Z\" \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String OPERATION_OUTCOME =
      "{ \n"
          + "    resourceType: \"OperationOutcome\", \n"
          + "    issue: [ \n"
          + "        { \n"
          + "            severity: \"error\", \n"
          + "            code: \"forbidden\", \n"
          + "            details: { \n"
          + "                text: \"Token not allowed access to this patient.\" \n"
          + "            } \n"
          + "        } \n"
          + "    ] \n"
          + "} \n";
  static final String MEDICATION =
      "{ \n"
          + "    resourceType: \"Medication\", \n"
          + "    id: \"f4163f35-1565-552b-a1b9-a2f8870e6f4a\", \n"
          + "    code: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"https://www.nlm.nih.gov/research/umls/rxnorm/\", \n"
          + "                code: \"895994\", \n"
          + "                display: \"120 Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "            } \n"
          + "        ], \n"
          + "        text: \"120 ACTUAT Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "    }, \n"
          + "    product: { \n"
          + "        id: \"4024655\", \n"
          + "        form: { \n"
          + "            text: \"1 dose(s) 1 time(s) per 1 days\" \n"
          + "        } \n"
          + "    } \n"
          + "} ";
  static final String PROCEDURE =
      "{ \n"
          + "   resourceType: \"Procedure\", \n"
          + "   id: \"532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "   subject: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   status: \"completed\", \n"
          + "   code: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            display: \"Documentation of current medications\", \n"
          + "            system: \"http://www.ama-assn.org/go/cpt\", \n"
          + "            code: \"XXXXX\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   notPerformed: \"false\", \n"
          + "   performedDateTime: \"2017-04-24T01:15:52Z\" \n"
          + "} ";
  static final String PROCEDURE_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Procedure\", \n"
          + "                    id: \"532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "                    subject: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    status: \"completed\", \n"
          + "                    code: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             display: \"Documentation of current medications\", \n"
          + "                             system: \"http://www.ama-assn.org/go/cpt\", \n"
          + "                             code: \"XXXXX\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    notPerformed: \"false\", \n"
          + "                    performedDateTime: \"2017-04-24T01:15:52Z\" \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String OBSERVATION =
      "{ \n"
          + "   resourceType: \"Observation\", \n"
          + "   id: \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "   status: \"final\", \n"
          + "   category: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/observation-category\", \n"
          + "            code: \"laboratory\", \n"
          + "            display: \"Laboratory\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   code: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://loinc.org\", \n"
          + "            code: \"32623-1\", \n"
          + "            display: \"Platelet mean volume [Entitic volume] in Blood by \" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   subject\": { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   effectiveDateTime: \"2017-04-24T01:15:52Z\", \n"
          + "   issued: \"2017-04-24T01:15:52Z\", \n"
          + "   valueQuantity: { \n"
          + "      value: 10.226877417360429, \n"
          + "      unit: \"fL\", \n"
          + "      system: \"http://unitsofmeasure.org\", \n"
          + "      code: \"fL\" \n"
          + "   } \n"
          + "} ";
  static final String OBSERVATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Observation\", \n"
          + "                    id: \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "                    status: \"final\", \n"
          + "                    category: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://hl7.org/fhir/observation-category\", \n"
          + "                             code: \"laboratory\", \n"
          + "                             display: \"Laboratory\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://loinc.org\", \n"
          + "                             code: \"32623-1\", \n"
          + "                             display: \"Platelet mean volume in Blood by \" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    subject\": { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    effectiveDateTime: \"2017-04-24T01:15:52Z\", \n"
          + "                    issued: \"2017-04-24T01:15:52Z\", \n"
          + "                    valueQuantity: { \n"
          + "                       value: 10.226877417360429, \n"
          + "                       unit: \"fL\", \n"
          + "                       system: \"http://unitsofmeasure.org\", \n"
          + "                       code: \"fL\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String MEDICATION_STATEMENT =
      "{ \n"
          + "   resourceType: \"MedicationStatement\", \n"
          + "   id: \"1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   dateAsserted: \"2013-04-15T01:15:52Z\", \n"
          + "   status: \"active\", \n"
          + "   medicationReference: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "      display: \"Hydrochlorothiazide 25 MG\" \n"
          + "   }, \n"
          + "   dosage: [ \n"
          + "      { \n"
          + "         text: \"Once per day.\", \n"
          + "         timing: { \n"
          + "            code: { \n"
          + "               text: \"As directed by physician.\" \n"
          + "            } \n"
          + "         }, \n"
          + "         route: { \n"
          + "            text: \"As directed by physician.\" \n"
          + "         } \n"
          + "      } \n"
          + "   ] \n"
          + "} ";
  static final String MEDICATION_STATEMENT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"MedicationStatement\", \n"
          + "                    id: \"1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    dateAsserted: \"2013-04-15T01:15:52Z\", \n"
          + "                    status: \"active\", \n"
          + "                    medicationReference: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "                       display: \"Hydrochlorothiazide 25 MG\" \n"
          + "                    }, \n"
          + "                    dosage: [ \n"
          + "                       { \n"
          + "                          text: \"Once per day.\", \n"
          + "                          timing: { \n"
          + "                             code: { \n"
          + "                                text: \"As directed by physician.\" \n"
          + "                             } \n"
          + "                          }, \n"
          + "                          route: { \n"
          + "                             text: \"As directed by physician.\" \n"
          + "                          } \n"
          + "                       } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String MEDICATION_ORDER =
      "{ \n"
          + "   resourceType: \"MedicationOrder\", \n"
          + "   id: \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "   dateWritten: \"2013-04-14T06:00:00Z\", \n"
          + "   status: \"active\", \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   _prescriber: { \n"
          + "       extension: [ \n"
          + "           { \n"
          + "               url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "               valueCode: \"unsupported\" \n"
          + "           } \n"
          + "       ] \n"
          + "   }, \n"
          + "   medicationReference: { \n"
          + "       reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "       display: \"Hydrochlorothiazide 25 MG\" \n"
          + "   } \n"
          + "} ";
  static final String MEDICATION_ORDER_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"MedicationOrder\", \n"
          + "                    id: \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "                    dateWritten: \"2013-04-14T06:00:00Z\", \n"
          + "                    status: \"active\", \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    _prescriber: { \n"
          + "                        extension: [ \n"
          + "                            { \n"
          + "                                url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "                                valueCode: \"unsupported\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    medicationReference: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "                        display: \"Hydrochlorothiazide 25 MG\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String DIAGNOSTIC_REPORT =
      "{ \n"
          + "   resourceType: \"DiagnosticReport\", \n"
          + "   id: \"0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "   status: \"final\", \n"
          + "   category: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", \n"
          + "            code: \"LAB\", \n"
          + "            display: \"Laboratory\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   code: { \n"
          + "      text: \"panel\" \n"
          + "   }, \n"
          + "   effectiveDateTime: \"2011-04-04T01:15:52Z\", \n"
          + "   issued: \"2011-04-04T01:15:52Z\", \n"
          + "   subject: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   } \n"
          + "} ";
  static final String DIAGNOSTIC_REPORT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"DiagnosticReport\", \n"
          + "                    id: \"0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "                    status: \"final\", \n"
          + "                    category: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", \n"
          + "                                code: \"LAB\", \n"
          + "                                display: \"Laboratory\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                        text: \"panel\" \n"
          + "                    }, \n"
          + "                    effectiveDateTime: \"2011-04-04T01:15:52Z\", \n"
          + "                    issued: \"2011-04-04T01:15:52Z\", \n"
          + "                    subject: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String IMMUNIZATION =
      "{ \n"
          + "   resourceType: \"Immunization\", \n"
          + "   id: \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "   status: \"completed\", \n"
          + "   date: \"2017-04-24T01:15:52Z\", \n"
          + "   vaccineCode: { \n"
          + "      text: \"meningococcal MCV4P\", \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/sid/cvx\", \n"
          + "            code: \"114\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   wasNotGiven: \"false\", \n"
          + "   _reported: { \n"
          + "      extension: [ \n"
          + "         { \n"
          + "            url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "            valueCode: \"unsupported\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   reaction: [ \n"
          + "      { \n"
          + "            detail: { \n"
          + "            display: \"Lethargy\" \n"
          + "         } \n"
          + "      } \n"
          + "   ] \n"
          + "} ";
  static final String IMMUNIZATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Immunization\", \n"
          + "                    id: \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "                    status: \"completed\", \n"
          + "                    date: \"2017-04-24T01:15:52Z\", \n"
          + "                    vaccineCode: { \n"
          + "                       text: \"meningococcal MCV4P\", \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://hl7.org/fhir/sid/cvx\", \n"
          + "                             code: \"114\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    wasNotGiven: \"false\", \n"
          + "                    _reported: { \n"
          + "                       extension: [ \n"
          + "                          { \n"
          + "                             url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "                             valueCode: \"unsupported\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    reaction: [ \n"
          + "                       { \n"
          + "                           detail: { \n"
          + "                               display: \"Lethargy\" \n"
          + "                           } \n"
          + "                       } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String PATIENT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", \n"
          + "                resource: { \n"
          + "                    id: \"2000163\", \n"
          + "                    resourceType: \"Patient\", \n"
          + "                    extension: [ \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", \n"
          + "                            extension: [ \n"
          + "                                { \n"
          + "                                    url: \"ombCategory\", \n"
          + "                                    valueCoding: { \n"
          + "                                        system: \"http://hl7.org/fhir/v3/Race\", \n"
          + "                                        code: \"2016-3\", \n"
          + "                                        display: \"White\" \n"
          + "                                    } \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    url: \"text\", \n"
          + "                                    valueString: \"White\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", \n"
          + "                            extension: [ \n"
          + "                                { \n"
          + "                                    url: \"ombCategory\", \n"
          + "                                    valueCoding: { \n"
          + "                                        system: \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", \n"
          + "                                        code: \"2186-5\", \n"
          + "                                        display: \"Not Hispanic or Latino\" \n"
          + "                                    } \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    url: \"text\", \n"
          + "                                    valueString: \"Not Hispanic or Latino\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", \n"
          + "                            valueCode: \"M\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    identifier: [ \n"
          + "                        { \n"
          + "                            use: \"usual\", \n"
          + "                            type: { \n"
          + "                                coding: [ \n"
          + "                                    { \n"
          + "                                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                                        code: \"MR\" \n"
          + "                                    } \n"
          + "                                ] \n"
          + "                            }, \n"
          + "                            system: \"http://va.gov/mvi\", \n"
          + "                            value: \"2000163\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            use: \"official\", \n"
          + "                            type: { \n"
          + "                                coding: [ \n"
          + "                                    { \n"
          + "                                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                                        code: \"SB\" \n"
          + "                                    } \n"
          + "                                ] \n"
          + "                            }, \n"
          + "                            system: \"http://hl7.org/fhir/sid/us-ssn\", \n"
          + "                            value: \"999-61-4803\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    name: [ \n"
          + "                        { \n"
          + "                            use: \"usual\", \n"
          + "                            text: \"Mr. Aurelio227 Cruickshank494\", \n"
          + "                            family: [ \n"
          + "                                \"Cruickshank494\" \n"
          + "                            ], \n"
          + "                            given: [ \n"
          + "                                \"Aurelio227\" \n"
          + "                            ] \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    telecom: [ \n"
          + "                        { \n"
          + "                            system: \"phone\", \n"
          + "                            value: \"5555191065\", \n"
          + "                            use: \"mobile\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            system: \"email\", \n"
          + "                            value: \"Aurelio227.Cruickshank494@email.example\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    gender: \"male\", \n"
          + "                    birthDate: \"1995-02-06\", \n"
          + "                    deceasedBoolean: \"false\", \n"
          + "                    address: [ \n"
          + "                        { \n"
          + "                            line: [ \n"
          + "                                \"909 Rohan Highlands\" \n"
          + "                            ], \n"
          + "                            city: \"Mesa\", \n"
          + "                            state: \"Arizona\", \n"
          + "                            postalCode: \"85120\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    maritalStatus: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://hl7.org/fhir/v3/NullFlavor\", \n"
          + "                                code: \"UNK\", \n"
          + "                                display: \"unknown\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String PATIENT =
      "{ \n"
          + "    id: \"2000163\", \n"
          + "    resourceType: \"Patient\", \n"
          + "    extension: [ \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", \n"
          + "            extension: [ \n"
          + "                { \n"
          + "                    url: \"ombCategory\", \n"
          + "                    valueCoding: { \n"
          + "                        system: \"http://hl7.org/fhir/v3/Race\", \n"
          + "                        code: \"2016-3\", \n"
          + "                        display: \"White\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                { \n"
          + "                    url: \"text\", \n"
          + "                    valueString: \"White\" \n"
          + "                } \n"
          + "            ] \n"
          + "        }, \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", \n"
          + "            extension: [ \n"
          + "                { \n"
          + "                    url: \"ombCategory\", \n"
          + "                    valueCoding: { \n"
          + "                        system: \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", \n"
          + "                        code: \"2186-5\", \n"
          + "                        display: \"Not Hispanic or Latino\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                { \n"
          + "                    url: \"text\", \n"
          + "                    valueString: \"Not Hispanic or Latino\" \n"
          + "                } \n"
          + "            ] \n"
          + "        }, \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", \n"
          + "            valueCode: \"M\" \n"
          + "        } \n"
          + "    ], \n"
          + "    identifier: [ \n"
          + "        { \n"
          + "            use: \"usual\", \n"
          + "            type: { \n"
          + "                coding: [ \n"
          + "                    { \n"
          + "                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                        code: \"MR\" \n"
          + "                    } \n"
          + "                ] \n"
          + "            }, \n"
          + "            system: \"http://va.gov/mvi\", \n"
          + "            value: \"2000163\" \n"
          + "        }, \n"
          + "        { \n"
          + "            use: \"official\", \n"
          + "            type: { \n"
          + "                coding: [ \n"
          + "                    { \n"
          + "                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                        code: \"SB\" \n"
          + "                    } \n"
          + "                ] \n"
          + "            }, \n"
          + "            system: \"http://hl7.org/fhir/sid/us-ssn\", \n"
          + "            value: \"999-61-4803\" \n"
          + "        } \n"
          + "    ], \n"
          + "    name: [ \n"
          + "        { \n"
          + "            use: \"usual\", \n"
          + "            text: \"Mr. Aurelio227 Cruickshank494\", \n"
          + "            family: [ \n"
          + "                \"Cruickshank494\" \n"
          + "            ], \n"
          + "            given: [ \n"
          + "                \"Aurelio227\" \n"
          + "            ] \n"
          + "        } \n"
          + "    ], \n"
          + "    telecom: [ \n"
          + "        { \n"
          + "            system: \"phone\", \n"
          + "            value: \"5555191065\", \n"
          + "            use: \"mobile\" \n"
          + "        }, \n"
          + "        { \n"
          + "            system: \"email\", \n"
          + "            value: \"Aurelio227.Cruickshank494@email.example\" \n"
          + "        } \n"
          + "    ], \n"
          + "    gender: \"male\", \n"
          + "    birthDate: \"1995-02-06\", \n"
          + "    deceasedBoolean: \"false\", \n"
          + "    address: [ \n"
          + "        { \n"
          + "            line: [ \n"
          + "                \"909 Rohan Highlands\" \n"
          + "            ], \n"
          + "            city: \"Mesa\", \n"
          + "            state: \"Arizona\", \n"
          + "            postalCode: \"85120\" \n"
          + "        } \n"
          + "    ], \n"
          + "    maritalStatus: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"http://hl7.org/fhir/v3/NullFlavor\", \n"
          + "                code: \"UNK\", \n"
          + "                display: \"unknown\" \n"
          + "            } \n"
          + "        ] \n"
          + "    } \n"
          + "} \n";
  static final String ALLERGY_INTOLERANCE =
      "{ \n"
          + "    resourceType: \"AllergyIntolerance\", \n"
          + "    id: \"6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", \n"
          + "    onset: \"1995-04-30T01:15:52Z\", \n"
          + "    patient: { \n"
          + "       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "    }, \n"
          + "    substance: { \n"
          + "        text: \"Allergy to peanuts\" \n"
          + "   }, \n"
          + "    status: \"active\", \n"
          + "    type: \"allergy\", \n"
          + "    category: \"food\", \n"
          + "    note: { \n"
          + "        time: \"1995-04-30T01:15:52Z\", \n"
          + "        text: \"Allergy to peanuts\" \n"
          + "    }, \n"
          + "    reaction: [ \n"
          + "        { \n"
          + "            manifestation: [ \n"
          + "                { \n"
          + "                    coding: [ \n"
          + "                        { \n"
          + "                            display: \"Inflammation of Skin\", \n"
          + "                            system: \"urn:oid:2.16.840.1.113883.6.233\", \n"
          + "                            code: \"2000001\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    text: \"Inflammation of Skin\" \n"
          + "                } \n"
          + "            ], \n"
          + "            certainty: \"likely\" \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String ALLERGY_INTOLERANCE_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/e2019e0c-fa38-596d-b966-9b86926959a7\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"AllergyIntolerance\", \n"
          + "                    id: \"e2019e0c-fa38-596d-b966-9b86926959a7\", \n"
          + "                    onset: \"1995-04-30T01:15:52Z\", \n"
          + "                    patient: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    substance: { \n"
          + "                        text: \"Allergy to bee venom\" \n"
          + "                    }, \n"
          + "                    status: \"active\", \n"
          + "                    type: \"allergy\", \n"
          + "                    note: { \n"
          + "                        time: \"1995-04-30T01:15:52Z\", \n"
          + "                        text: \"Allergy to bee venom\" \n"
          + "                    }, \n"
          + "                    reaction: [ \n"
          + "                        { \n"
          + "                            manifestation: [ \n"
          + "                                { \n"
          + "                                    coding: [ \n"
          + "                                        { \n"
          + "                                            display: \"Sneezing and Coughing\", \n"
          + "                                            system: \"urn:oid:2.16.840.1.233\", \n"
          + "                                            code: \"2000004\" \n"
          + "                                        } \n"
          + "                                    ], \n"
          + "                                    text: \"Sneezing and Coughing\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
}
