package gov.va.api.health.argonaut.api.resources;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/** Samples for swagger documentation. */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
class SwaggerExamples {

  static final String ALLERGY_INTOLERANCE =
      "{ "
          + "    \"resourceType\": \"AllergyIntolerance\", "
          + "    \"id\": \"6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", "
          + "    \"onset\": \"1995-04-30T01:15:52Z\", "
          + "    \"patient\": { "
          + "       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "        \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "    }, "
          + "    \"substance\": { "
          + "        \"text\": \"Allergy to peanuts\" "
          + "   }, "
          + "    \"status\": \"active\", "
          + "    \"type\": \"allergy\", "
          + "    \"category\": \"food\", "
          + "    \"note\": { "
          + "        \"time\": \"1995-04-30T01:15:52Z\", "
          + "        \"text\": \"Allergy to peanuts\" "
          + "    }, "
          + "    \"reaction\": [ "
          + "        { "
          + "            \"manifestation\": [ "
          + "                { "
          + "                    \"coding\": [ "
          + "                        { "
          + "                            \"display\": \"Inflammation of Skin\", "
          + "                            \"system\": \"urn:oid:2.16.840.1.113883.6.233\", "
          + "                            \"code\": \"2000001\" "
          + "                        } "
          + "                    ], "
          + "                    \"text\": \"Inflammation of Skin\" "
          + "                } "
          + "            ], "
          + "            \"certainty\": \"likely\" "
          + "        } "
          + "    ] "
          + "} ";
  static final String ALLERGY_INTOLERANCE_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/e2019e0c-fa38-596d-b966-9b86926959a7\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"AllergyIntolerance\", "
          + "                    \"id\": \"e2019e0c-fa38-596d-b966-9b86926959a7\", "
          + "                    \"onset\": \"1995-04-30T01:15:52Z\", "
          + "                    \"patient\": { "
          + "                        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                        \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"substance\": { "
          + "                        \"text\": \"Allergy to bee venom\" "
          + "                    }, "
          + "                    \"status\": \"active\", "
          + "                    \"type\": \"allergy\", "
          + "                    \"note\": { "
          + "                        \"time\": \"1995-04-30T01:15:52Z\", "
          + "                        \"text\": \"Allergy to bee venom\" "
          + "                    }, "
          + "                    \"reaction\": [ "
          + "                        { "
          + "                            \"manifestation\": [ "
          + "                                { "
          + "                                    \"coding\": [ "
          + "                                        { "
          + "                                            \"display\": \"Sneezing and Coughing\", "
          + "                                            \"system\": \"urn:oid:2.16.840.1.233\", "
          + "                                            \"code\": \"2000004\" "
          + "                                        } "
          + "                                    ], "
          + "                                    \"text\": \"Sneezing and Coughing\" "
          + "                                } "
          + "                            ] "
          + "                        } "
          + "                    ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String APPOINTMENT =
      " { "
          + "   \"resourceType\": \"Appointment\", "
          + "   \"id\": \"0be173b4-721c-554e-ba7d-966d04633b68\", "
          + "   \"status\": \"cancelled\", "
          + "   \"description\": \"Scheduled Visit\", "
          + "   \"start\": \"2006-06-30T17:00:00Z\", "
          + "   \"participant\": [ "
          + "     { "
          + "       \"type\": [ "
          + "         { "
          + "           \"system\": \"http://hl7.org/fhir/v3/ParticipationType\", "
          + "           \"code\": \"PART\", "
          + "           \"display\": \"Participation\" "
          + "         } "
          + "       ], "
          + "       \"actor\": { "
          + "         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", "
          + "         \"display\": \"VETERAN,JOHN Q\" "
          + "       }, "
          + "       \"required\": \"required\", "
          + "       \"status\": \"accepted\" "
          + "     }, "
          + "     { "
          + "       \"type\": [ "
          + "         { "
          + "           \"system\": \"http://hl7.org/fhir/v3/ParticipationType\", "
          + "           \"code\": \"PART\", "
          + "           \"display\": \"Participation\" "
          + "         } "
          + "       ], "
          + "       \"actor\": { "
          + "         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Location/71fed7fc-d060-5a35-bba9-e89fd7cdb4e6\", "
          + "         \"display\": \"ZZZTG SURG POD SCHEULLER COBI\" "
          + "       }, "
          + "       \"required\": \"required\", "
          + "       \"status\": \"accepted\" "
          + "     } "
          + "   ] "
          + " } ";

  static final String APPOINTMENT_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Appointment/0be173b4-721c-554e-ba7d-966d04633b68\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Appointment/0be173b4-721c-554e-ba7d-966d04633b68\", "
          + "                \"resource\": { "
          + "                      \"resourceType\": \"Appointment\", "
          + "                      \"id\": \"0be173b4-721c-554e-ba7d-966d04633b68\", "
          + "                      \"status\": \"cancelled\", "
          + "                      \"description\": \"Scheduled Visit\", "
          + "                      \"start\": \"2006-06-30T17:00:00Z\", "
          + "                      \"participant\": [ "
          + "                        { "
          + "                          \"type\": [ "
          + "                            { "
          + "                              \"system\": \"http://hl7.org/fhir/v3/ParticipationType\", "
          + "                              \"code\": \"PART\", "
          + "                              \"display\": \"Participation\" "
          + "                            } "
          + "                          ], "
          + "                          \"actor\": { "
          + "                            \"reference\": \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", "
          + "                            \"display\": \"VETERAN,JOHN Q\" "
          + "                          }, "
          + "                          \"required\": \"required\", "
          + "                          \"status\": \"accepted\" "
          + "                        }, "
          + "                        { "
          + "                          \"type\": [ "
          + "                            { "
          + "                              \"system\": \"http://hl7.org/fhir/v3/ParticipationType\", "
          + "                              \"code\": \"PART\", "
          + "                              \"display\": \"Participation\" "
          + "                            } "
          + "                          ], "
          + "                          \"actor\": { "
          + "                            \"reference\": \"https://www.freedomstream.io/Argonaut/api/Location/71fed7fc-d060-5a35-bba9-e89fd7cdb4e6\", "
          + "                            \"display\": \"ZZZTG SURG POD SCHEULLER COBI\" "
          + "                          }, "
          + "                          \"required\": \"required\", "
          + "                          \"status\": \"accepted\" "
          + "                        } "
          + "                      ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "        } "
          + "    ] "
          + "} ";

  static final String CONDITION =
      "{ "
          + "    \"resourceType\": \"Condition\", "
          + "    \"id\": \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", "
          + "    \"patient\": { "
          + "        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "        \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "    }, "
          + "    \"code\": { "
          + "        \"coding\": [ "
          + "            { "
          + "                \"code\": \"38341003\", "
          + "                \"system\": \"https://www.snomed.org/snomed-ct\", "
          + "                \"display\": \"Hypertension\" "
          + "            } "
          + "        ], "
          + "        \"text\": \"Hypertension\" "
          + "    }, "
          + "    \"category\": { "
          + "        \"coding\": [ "
          + "            { "
          + "                \"system\": \"http://argonaut.hl7.org\", "
          + "                \"code\": \"problem\" "
          + "            } "
          + "        ] "
          + "    }, "
          + "    \"clinicalStatus\": \"active\", "
          + "    \"verificationStatus\": \"unknown\", "
          + "    \"dateRecorded\": \"2013-04-14\", "
          + "    \"onsetDateTime\": \"2013-04-15T01:15:52Z\" "
          + "} ";
  static final String CONDITION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Condition\", "
          + "                    \"id\": \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", "
          + "                    \"patient\": { "
          + "                        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                        \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"code\": { "
          + "                        \"coding\": [ "
          + "                           { "
          + "                               \"code\": \"38341003\", "
          + "                               \"system\": \"https://www.snomed.org/snomed-ct\", "
          + "                               \"display\": \"Hypertension\" "
          + "                           } "
          + "                        ], "
          + "                        \"text\": \"Hypertension\" "
          + "                    }, "
          + "                    \"category\": { "
          + "                        \"coding\": [ "
          + "                            { "
          + "                                \"system\": \"http://argonaut.hl7.org\", "
          + "                                \"code\": \"problem\" "
          + "                            } "
          + "                        ] "
          + "                    }, "
          + "                    \"clinicalStatus\": \"active\", "
          + "                    \"verificationStatus\": \"unknown\", "
          + "                    \"dateRecorded\": \"2013-04-14\", "
          + "                    \"onsetDateTime\": \"2013-04-15T01:15:52Z\" "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String ENCOUNTER =
      "{ "
          + "  \"resourceType\": \"Encounter\", "
          + "  \"id\": \"dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", "
          + "  \"status\": \"finished\", "
          + "  \"class\": \"emergency\", "
          + "  \"patient\": { "
          + "    \"reference\": \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", "
          + "    \"display\": \"VETERAN,JOHN Q\" "
          + "  }, "
          + "  \"participant\": [ "
          + "    { "
          + "      \"individual\": { "
          + "        \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/d3f56fac-c7c7-547b-a1e9-de3173d4b628\", "
          + "        \"display\": \"CARTER,DOC F\" "
          + "      } "
          + "    }, "
          + "    { "
          + "      \"individual\": { "
          + "        \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/93e4e3c3-8d8c-5b53-996f-6047d0232231\", "
          + "        \"display\": \"JONES,DOC B "
          + "      } "
          + "    }, "
          + "    { "
          + "      \"individual\": { "
          + "        \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/5e27c469-82e4-5725-babb-49cf7eee948f\", "
          + "        \"display\": CARTER,DOC F\" "
          + "      } "
          + "    }, "
          + "    { "
          + "      \"individual\": { "
          + "        \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/1b489f04-19e7-5c7d-9140-ce773c158edd\", "
          + "        \"display\": \"SMITH,DOC A\" "
          + "      } "
          + "    } "
          + "  ], "
          + "  \"appointment\": { "
          + "    \"reference\": \"https://www.freedomstream.io/Argonaut/api/Appointment/615f31df-f0c7-5100-ac42-7fb952c630d0\" "
          + "  }, "
          + "  \"indication\": [ "
          + "    { "
          + "      \"reference\": \"https://www.freedomstream.io/Argonaut/api/Condition/37d89dc5-45f5-5a2e-9db9-2b17c0d7f318\", "
          + "      \"display\": \"Chronic asthmatic bronchitis (SNOMED CT 195949008)\" "
          + "    } "
          + "  ], "
          + "  \"location\": [ "
          + "    { "
          + "      \"location\": { "
          + "        \"reference\": \"https://www.freedomstream.io/Argonaut/api/Location/eb094a51-ad31-5b6b-b627-96aac4b02b1c\", "
          + "        \"display\": \"GNV ED\" "
          + "      } "
          + "    } "
          + "  ], "
          + "  \"serviceProvider\": { "
          + "    \"reference\": \"https://www.freedomstream.io/Argonaut/api/Institution/ed3f9a41-397a-5100-b177-ae3815e5c370\", "
          + "    \"display\": \"N. FLORIDA/S. GEORGIA HCS\" "
          + "  } "
          + "} ";

  static final String ENCOUNTER_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Encounter/dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Encounter/dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", "
          + "                \"resource\": { "
          + "                   \"resourceType\": \"Encounter\", "
          + "                   \"id\": \"dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", "
          + "                   \"status\": \"finished\", "
          + "                   \"class\": \"emergency\", "
          + "                   \"patient\": { "
          + "                     \"reference\": \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", "
          + "                     \"display\": \"VETERAN,JOHN Q\" "
          + "                   }, "
          + "                   \"participant\": [ "
          + "                     { "
          + "                       \"individual\": { "
          + "                         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/d3f56fac-c7c7-547b-a1e9-de3173d4b628\", "
          + "                         \"display\": \"CARTER,DOC F\" "
          + "                       } "
          + "                     }, "
          + "                     { "
          + "                       \"individual\": { "
          + "                         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/93e4e3c3-8d8c-5b53-996f-6047d0232231\", "
          + "                         \"display\": \"JONES,DOC B "
          + "                       } "
          + "                     }, "
          + "                     { "
          + "                       \"individual\": { "
          + "                         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/5e27c469-82e4-5725-babb-49cf7eee948f\", "
          + "                         \"display\": CARTER,DOC F\" "
          + "                       } "
          + "                     }, "
          + "                     { "
          + "                       \"individual\": { "
          + "                         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Practitioner/1b489f04-19e7-5c7d-9140-ce773c158edd\", "
          + "                         \"display\": \"SMITH,DOC A\" "
          + "                       } "
          + "                     } "
          + "                   ], "
          + "                   \"appointment\": { "
          + "                     \"reference\": \"https://www.freedomstream.io/Argonaut/api/Appointment/615f31df-f0c7-5100-ac42-7fb952c630d0\" "
          + "                   }, "
          + "                   \"indication\": [ "
          + "                     { "
          + "                       \"reference\": \"https://www.freedomstream.io/Argonaut/api/Condition/37d89dc5-45f5-5a2e-9db9-2b17c0d7f318\", "
          + "                       \"display\": \"Chronic asthmatic bronchitis (SNOMED CT 195949008)\" "
          + "                     } "
          + "                   ], "
          + "                   \"location\": [ "
          + "                     { "
          + "                       \"location\": { "
          + "                         \"reference\": \"https://www.freedomstream.io/Argonaut/api/Location/eb094a51-ad31-5b6b-b627-96aac4b02b1c\", "
          + "                         \"display\": \"GNV ED\" "
          + "                       } "
          + "                     } "
          + "                   ], "
          + "                   \"serviceProvider\": { "
          + "                     \"reference\": \"https://www.freedomstream.io/Argonaut/api/Institution/ed3f9a41-397a-5100-b177-ae3815e5c370\", "
          + "                     \"display\": \"N. FLORIDA/S. GEORGIA HCS\" "
          + "                   } "
          + "            }, "
          + "            \"search\": { "
          + "                \"mode\": \"match\" "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String LOCATION =
      "{ "
          + "  \"resourceType\": \"Location\", "
          + "  \"id\": \"96aee2f5-a2ce-588f-8352-f6ea61f0959d\", "
          + "  \"status\": \"active\", "
          + "  \"name\": \"VAMC ALBANY\", "
          + "  \"description\": \"VAMC ALBANY\", "
          + "  \"mode\": \"instance\", "
          + "  \"address\": { "
          + "    \"line\": [ "
          + "      \"113 Holland Avenue\" "
          + "    ], "
          + "    \"city\": \"ALBANY\", "
          + "    \"state\": \"NEW YORK\" "
          + "  }, "
          + "  \"managingOrganization\": { "
          + "    \"reference\": \"https://www.freedomstream.io/Argonaut/api/Organization/e207c621-f467-5983-a6d1-868f33cefa95\", "
          + "    \"display\": \"ZZ ALBANY\" "
          + "  } "
          + "} ";

  static final String LOCATION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Location/96aee2f5-a2ce-588f-8352-f6ea61f0959d\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Location/96aee2f5-a2ce-588f-8352-f6ea61f0959d\", "
          + "                \"resource\": { "
          + "                  \"resourceType\": \"Location\", "
          + "                  \"id\": \"96aee2f5-a2ce-588f-8352-f6ea61f0959d\", "
          + "                  \"status\": \"active\", "
          + "                  \"name\": \"VAMC ALBANY\", "
          + "                  \"description\": \"VAMC ALBANY\", "
          + "                  \"mode\": \"instance\", "
          + "                  \"address\": { "
          + "                    \"line\": [ "
          + "                      \"113 Holland Avenue\" "
          + "                    ], "
          + "                    \"city\": \"ALBANY\", "
          + "                    \"state\": \"NEW YORK\" "
          + "                  }, "
          + "                  \"managingOrganization\": { "
          + "                    \"reference\": \"https://www.freedomstream.io/Argonaut/api/Organization/e207c621-f467-5983-a6d1-868f33cefa95\", "
          + "                    \"display\": \"ZZ ALBANY\" "
          + "                  } "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "        } "
          + "    ] "
          + "} ";

  static final String OPERATION_OUTCOME =
      "{ "
          + "    \"resourceType\": \"OperationOutcome\", "
          + "    \"issue\": [ "
          + "        { "
          + "            \"severity\": \"error\", "
          + "            \"code\": \"forbidden\", "
          + "            \"details\": { "
          + "                \"text\": \"Token not allowed access to this patient.\" "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String MEDICATION =
      "{ "
          + "    \"resourceType\": \"Medication\", "
          + "    \"id\": \"f4163f35-1565-552b-a1b9-a2f8870e6f4a\", "
          + "    \"code\": { "
          + "        \"coding\": [ "
          + "            { "
          + "                \"system\": \"https://www.nlm.nih.gov/research/umls/rxnorm/\", "
          + "                \"code\": \"895994\", "
          + "                \"display\": \"120 Fluticasone propionate .044 MG/ACTUAT Inhaler\" "
          + "            } "
          + "        ], "
          + "        \"text\": \"120 ACTUAT Fluticasone propionate .044 MG/ACTUAT Inhaler\" "
          + "    }, "
          + "    \"product\": { "
          + "        \"id\": \"4024655\", "
          + "        \"form\": { "
          + "            \"text\": \"1 dose(s) 1 time(s) per 1 days\" "
          + "        } "
          + "    } "
          + "} ";

  static final String MEDICATION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/f4163f35-1565-552b-a1b9-a2f8870e6f4a\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/f4163f35-1565-552b-a1b9-a2f8870e6f4a\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Medication\", "
          + "                    \"id\": \"f4163f35-1565-552b-a1b9-a2f8870e6f4a\", "
          + "                    \"code\": { "
          + "                        \"coding\": [ "
          + "                            { "
          + "                                \"system\": \"https://www.nlm.nih.gov/research/umls/rxnorm/\", "
          + "                                \"code\": \"895994\", "
          + "                                \"display\": \"120 Fluticasone propionate .044 MG/ACTUAT Inhaler\" "
          + "                            } "
          + "                        ], "
          + "                        \"text\": \"120 ACTUAT Fluticasone propionate .044 MG/ACTUAT Inhaler\" "
          + "                    }, "
          + "                    \"product\": { "
          + "                        \"id\": \"4024655\", "
          + "                        \"form\": { "
          + "                            \"text\": \"1 dose(s) 1 time(s) per 1 days\" "
          + "                        } "
          + "                    } "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "        } "
          + "    ] "
          + "} ";

  static final String PROCEDURE =
      "{ "
          + "   \"resourceType\": \"Procedure\", "
          + "   \"id\": \"532070f1-cb7b-582e-9380-9e0ef27bc817\", "
          + "   \"subject\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   }, "
          + "   \"status\": \"completed\", "
          + "   \"code\": { "
          + "      \"coding\": [ "
          + "         { "
          + "            \"display\": \"Documentation of current medications\", "
          + "            \"system\": \"http://www.ama-assn.org/go/cpt\", "
          + "            \"code\": \"XXXXX\" "
          + "         } "
          + "      ] "
          + "   }, "
          + "   \"notPerformed\": \"false\", "
          + "   \"performedDateTime\": \"2017-04-24T01:15:52Z\" "
          + "} ";

  static final String MEDICATION_DISPENSE =
      "{\n"
          + "    \"resourceType\": \"MedicationDispense\",\n"
          + "    \"id\": \"3ba8c63c-bac2-5f98-b7cd-161792919216\",\n"
          + "    \"identifier\": {\n"
          + "        \"use\": \"usual\",\n"
          + "        \"system\": \"http://va.gov/cdw\",\n"
          + "        \"value\": \"185601V825290\"\n"
          + "    },\n"
          + "    \"status\": \"completed\",\n"
          + "    \"patient\": {\n"
          + "        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/185601V825290\",\n"
          + "        \"display\": \"VETERAN,JOHN Q\"\n"
          + "    },\n"
          + "    \"dispenser\": {\n"
          + "        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/a98d6c9c-c5bd-58a5-a5d0-0da31cafd37c\",\n"
          + "        \"display\": \"SMITH,ATTENDING C\"\n"
          + "    },\n"
          + "    \"authorizingPrescription\": [\n"
          + "        {\n"
          + "            \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/8c95153c-817b-53f3-8166-55b1e01ac2a2\",\n"
          + "            \"display\": \"OUTPATIENT PHARMACY\"\n"
          + "        }\n"
          + "    ],\n"
          + "    \"type\": {\n"
          + "        \"coding\": [\n"
          + "            {\n"
          + "                \"system\": \"http://hl7.org/fhir/v3/ActCode\",\n"
          + "                \"code\": \"FF\",\n"
          + "                \"display\": \"First Fill\"\n"
          + "            }\n"
          + "        ]\n"
          + "    },\n"
          + "    \"quantity\": {\n"
          + "        \"value\": 240,\n"
          + "        \"unit\": \"ML\"\n"
          + "    },\n"
          + "    \"daysSupply\": {\n"
          + "        \"value\": 15,\n"
          + "        \"unit\": \"Day\",\n"
          + "        \"system\": \"http://unitsofmeasure.org\",\n"
          + "        \"code\": \"D\"\n"
          + "    },\n"
          + "    \"medicationReference\": {\n"
          + "        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/b07873cb-24cb-5aa7-a0be-78b7ac5aee22\",\n"
          + "        \"display\": \"CODEINE 10/GG 100MG/5ML (ALC-F/SF) LIQ\"\n"
          + "    },\n"
          + "    \"whenPrepared\": \"2015-04-15T04:00:00Z\",\n"
          + "    \"dosageInstruction\": [\n"
          + "        {\n"
          + "            \"text\": \"TAKE 1 TEASPOONFUL BY MOUTH EVERY 6 HOURS AS NEEDED FOR COUGH CAN TAKE  2 TEASPOONS AT BEDTIME IF NEEDED. USE SPARINGLY\",\n"
          + "            \"additionalInstructions\": {\n"
          + "                \"text\": \"FOR COUGH can take 2 teaspoons at bedtime if needed. Use sparingly\"\n"
          + "            },\n"
          + "            \"timing\": {\n"
          + "                \"code\": {\n"
          + "                    \"text\": \"PRN\"\n"
          + "                }\n"
          + "            },\n"
          + "            \"asNeededBoolean\": true,\n"
          + "            \"route\": {\n"
          + "                \"text\": \"ORAL\"\n"
          + "            },\n"
          + "            \"doseQuantity\": {\n"
          + "                \"value\": 1\n"
          + "            }\n"
          + "        }\n"
          + "    ]\n"
          + "}";

  static final String MEDICATION_DISPENSE_BUNDLE =
      "{\n"
          + "    \"resourceType\": \"Bundle\",\n"
          + "    \"type\": \"searchset\",\n"
          + "    \"total\": 1155,\n"
          + "    \"link\": [\n"
          + "        {\n"
          + "            \"relation\": \"first\",\n"
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationDispense?patient=185601V825290&page=1&_count=1\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"relation\": \"self\",\n"
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationDispense?patient=185601V825290&page=1&_count=1\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"relation\": \"next\",\n"
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationDispense?patient=185601V825290&page=2&_count=1\"\n"
          + "        },\n"
          + "        {\n"
          + "            \"relation\": \"last\",\n"
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationDispense?patient=185601V825290&page=1155&_count=1\"\n"
          + "        }\n"
          + "    ],\n"
          + "    \"entry\": [\n"
          + "        {\n"
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationDispense/2f587c16-5182-59a5-bdcb-518c7c501f37\",\n"
          + "            \"resource\": {\n"
          + "                \"resourceType\": \"MedicationDispense\",\n"
          + "                \"id\": \"2f587c16-5182-59a5-bdcb-518c7c501f37\",\n"
          + "                \"identifier\": {\n"
          + "                    \"use\": \"usual\",\n"
          + "                    \"system\": \"http://va.gov/cdw\",\n"
          + "                    \"value\": \"185601V825290\"\n"
          + "                },\n"
          + "                \"status\": \"completed\",\n"
          + "                \"patient\": {\n"
          + "                    \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/185601V825290\",\n"
          + "                    \"display\": \"VETERAN,JOHN Q\"\n"
          + "                },\n"
          + "                \"dispenser\": {\n"
          + "                    \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/f3276418-063d-52d8-a7f9-5fcaadc2f22b\",\n"
          + "                    \"display\": \"BONES,ATTENDING C\"\n"
          + "                },\n"
          + "                \"authorizingPrescription\": [\n"
          + "                    {\n"
          + "                        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/e4638ac7-7af1-587c-8f93-811abf8158c7\",\n"
          + "                        \"display\": \"OUTPATIENT PHARMACY\"\n"
          + "                    }\n"
          + "                ],\n"
          + "                \"type\": {\n"
          + "                    \"coding\": [\n"
          + "                        {\n"
          + "                            \"system\": \"http://hl7.org/fhir/v3/ActCode\",\n"
          + "                            \"code\": \"FF\",\n"
          + "                            \"display\": \"First Fill\"\n"
          + "                        }\n"
          + "                    ]\n"
          + "                },\n"
          + "                \"quantity\": {\n"
          + "                    \"value\": 2,\n"
          + "                    \"unit\": \"EA\"\n"
          + "                },\n"
          + "                \"daysSupply\": {\n"
          + "                    \"value\": 30,\n"
          + "                    \"unit\": \"Day\",\n"
          + "                    \"system\": \"http://unitsofmeasure.org\",\n"
          + "                    \"code\": \"D\"\n"
          + "                },\n"
          + "                \"medicationReference\": {\n"
          + "                    \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/8ab05080-af33-5724-a090-e9f76386ce30\",\n"
          + "                    \"display\": \"ALBUTEROL 90MCG (CFC-F) 200D ORAL INHL\"\n"
          + "                },\n"
          + "                \"whenPrepared\": \"2015-04-15T04:00:00Z\",\n"
          + "                \"dosageInstruction\": [\n"
          + "                    {\n"
          + "                        \"text\": \"INHALE 2 PUFFS BY MOUTH EVERY 4 HOURS AS NEEDED FOR SHORTNESS OF  BREATH\",\n"
          + "                        \"timing\": {\n"
          + "                            \"code\": {\n"
          + "                                \"text\": \"Q4H PRN\"\n"
          + "                            }\n"
          + "                        },\n"
          + "                        \"asNeededBoolean\": true,\n"
          + "                        \"route\": {\n"
          + "                            \"text\": \"INHALATION ORAL\"\n"
          + "                        },\n"
          + "                        \"doseQuantity\": {\n"
          + "                            \"value\": 2\n"
          + "                        }\n"
          + "                    }\n"
          + "                ]\n"
          + "            },\n"
          + "            \"search\": {\n"
          + "                \"mode\": \"match\"\n"
          + "            }\n"
          + "        }\n"
          + "    ]\n"
          + "}";
  static final String PROCEDURE_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Procedure\", "
          + "                    \"id\": \"532070f1-cb7b-582e-9380-9e0ef27bc817\", "
          + "                    \"subject\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                       \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"status\": \"completed\", "
          + "                    \"code\": { "
          + "                       \"coding\": [ "
          + "                          { "
          + "                             \"display\": \"Documentation of current medications\", "
          + "                             \"system\": \"http://www.ama-assn.org/go/cpt\", "
          + "                             \"code\": \"XXXXX\" "
          + "                          } "
          + "                       ] "
          + "                    }, "
          + "                    \"notPerformed\": \"false\", "
          + "                    \"performedDateTime\": \"2017-04-24T01:15:52Z\" "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";
  static final String OBSERVATION =
      "{ "
          + "   \"resourceType\": \"Observation\", "
          + "   \"id\": \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", "
          + "   \"status\": \"final\", "
          + "   \"category\": { "
          + "      \"coding\": [ "
          + "         { "
          + "            \"system\": \"http://hl7.org/fhir/observation-category\", "
          + "            \"code\": \"laboratory\", "
          + "            \"display\": \"Laboratory\" "
          + "         } "
          + "      ] "
          + "   }, "
          + "   \"code\": { "
          + "      \"coding\": [ "
          + "         { "
          + "            \"system\": \"http://loinc.org\", "
          + "            \"code\": \"32623-1\", "
          + "            \"display\": \"Platelet mean volume [Entitic volume] in Blood by \" "
          + "         } "
          + "      ] "
          + "   }, "
          + "  \"subject\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   }, "
          + "   \"effectiveDateTime\": \"2017-04-24T01:15:52Z\", "
          + "   \"issued\": \"2017-04-24T01:15:52Z\", "
          + "   \"valueQuantity\": { "
          + "      \"value\": 10.226877417360429, "
          + "      \"unit\": \"fL\", "
          + "      \"system\": \"http://unitsofmeasure.org\", "
          + "      \"code\": \"fL\" "
          + "   } "
          + "} ";
  static final String OBSERVATION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Observation\", "
          + "                    \"id\": \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", "
          + "                    \"status\": \"final\", "
          + "                    \"category\": { "
          + "                       \"coding\": [ "
          + "                          { "
          + "                             \"system\": \"http://hl7.org/fhir/observation-category\", "
          + "                             \"code\": \"laboratory\", "
          + "                             \"display\": \"Laboratory\" "
          + "                          } "
          + "                       ] "
          + "                    }, "
          + "                    \"code\": { "
          + "                       \"coding\": [ "
          + "                          { "
          + "                             \"system\": \"http://loinc.org\", "
          + "                             \"code\": \"32623-1\", "
          + "                             \"display\": \"Platelet mean volume in Blood by \" "
          + "                          } "
          + "                       ] "
          + "                    }, "
          + "                   \"subject\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                       \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"effectiveDateTime\": \"2017-04-24T01:15:52Z\", "
          + "                    \"issued\": \"2017-04-24T01:15:52Z\", "
          + "                    \"valueQuantity\": { "
          + "                       \"value\": 10.226877417360429, "
          + "                       \"unit\": \"fL\", "
          + "                       \"system\": \"http://unitsofmeasure.org\", "
          + "                       \"code\": \"fL\" "
          + "                    } "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";
  static final String MEDICATION_STATEMENT =
      "{ "
          + "   \"resourceType\": \"MedicationStatement\", "
          + "   \"id\": \"1f46363d-af9b-5ba5-acda-b384373a9af2\", "
          + "   \"patient\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   }, "
          + "   \"dateAsserted\": \"2013-04-15T01:15:52Z\", "
          + "   \"status\": \"active\", "
          + "   \"medicationReference\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", "
          + "      \"display\": \"Hydrochlorothiazide 25 MG\" "
          + "   }, "
          + "   \"dosage\": [ "
          + "      { "
          + "         \"text\": \"Once per day.\", "
          + "         \"timing\": { "
          + "            \"code\": { "
          + "               \"text\": \"As directed by physician.\" "
          + "            } "
          + "         }, "
          + "         \"route\": { "
          + "            \"text\": \"As directed by physician.\" "
          + "         } "
          + "      } "
          + "   ] "
          + "} ";
  static final String MEDICATION_STATEMENT_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"MedicationStatement\", "
          + "                    \"id\": \"1f46363d-af9b-5ba5-acda-b384373a9af2\", "
          + "                    \"patient\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                       \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"dateAsserted\": \"2013-04-15T01:15:52Z\", "
          + "                    \"status\": \"active\", "
          + "                    \"medicationReference\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", "
          + "                       \"display\": \"Hydrochlorothiazide 25 MG\" "
          + "                    }, "
          + "                    \"dosage\": [ "
          + "                       { "
          + "                          \"text\": \"Once per day.\", "
          + "                          \"timing\": { "
          + "                             \"code\": { "
          + "                                \"text\": \"As directed by physician.\" "
          + "                             } "
          + "                          }, "
          + "                          \"route\": { "
          + "                             \"text\": \"As directed by physician.\" "
          + "                          } "
          + "                       } "
          + "                    ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";
  static final String MEDICATION_ORDER =
      "{ "
          + "   \"resourceType\": \"MedicationOrder\", "
          + "   \"id\": \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", "
          + "   \"dateWritten\": \"2013-04-14T06:00:00Z\", "
          + "   \"status\": \"active\", "
          + "   \"patient\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   }, "
          + "   \"_prescriber\": { "
          + "       \"extension\": [ "
          + "           { "
          + "               \"url\": \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", "
          + "               \"valueCode\": \"unsupported\" "
          + "           } "
          + "       ] "
          + "   }, "
          + "   \"medicationReference\": { "
          + "       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", "
          + "       \"display\": \"Hydrochlorothiazide 25 MG\" "
          + "   } "
          + "} ";
  static final String MEDICATION_ORDER_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"MedicationOrder\", "
          + "                    \"id\": \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", "
          + "                    \"dateWritten\": \"2013-04-14T06:00:00Z\", "
          + "                    \"status\": \"active\", "
          + "                    \"patient\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                       \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"_prescriber\": { "
          + "                        \"extension\": [ "
          + "                            { "
          + "                                \"url\": \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", "
          + "                                \"valueCode\": \"unsupported\" "
          + "                            } "
          + "                        ] "
          + "                    }, "
          + "                    \"medicationReference\": { "
          + "                        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", "
          + "                        \"display\": \"Hydrochlorothiazide 25 MG\" "
          + "                    } "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";
  static final String DIAGNOSTIC_REPORT =
      "{ "
          + "   \"resourceType\": \"DiagnosticReport\", "
          + "   \"id\": \"0757389a-6e06-51bd-aac0-bd0244e51e46\", "
          + "   \"status\": \"final\", "
          + "   \"category\": { "
          + "      \"coding\": [ "
          + "         { "
          + "            \"system\": \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", "
          + "            \"code\": \"LAB\", "
          + "            \"display\": \"Laboratory\" "
          + "         } "
          + "      ] "
          + "   }, "
          + "   \"code\": { "
          + "      \"text\": \"panel\" "
          + "   }, "
          + "   \"effectiveDateTime\": \"2011-04-04T01:15:52Z\", "
          + "   \"issued\": \"2011-04-04T01:15:52Z\", "
          + "   \"subject\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   } "
          + "} ";
  static final String DIAGNOSTIC_REPORT_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"DiagnosticReport\", "
          + "                    \"id\": \"0757389a-6e06-51bd-aac0-bd0244e51e46\", "
          + "                    \"status\": \"final\", "
          + "                    \"category\": { "
          + "                        \"coding\": [ "
          + "                            { "
          + "                                \"system\": \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", "
          + "                                \"code\": \"LAB\", "
          + "                                \"display\": \"Laboratory\" "
          + "                            } "
          + "                        ] "
          + "                    }, "
          + "                    \"code\": { "
          + "                        \"text\": \"panel\" "
          + "                    }, "
          + "                    \"effectiveDateTime\": \"2011-04-04T01:15:52Z\", "
          + "                    \"issued\": \"2011-04-04T01:15:52Z\", "
          + "                    \"subject\": { "
          + "                        \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                        \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    } "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";
  static final String IMMUNIZATION =
      "{ "
          + "   \"resourceType\": \"Immunization\", "
          + "   \"id\": \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", "
          + "   \"status\": \"completed\", "
          + "   \"date\": \"2017-04-24T01:15:52Z\", "
          + "   \"vaccineCode\": { "
          + "      \"text\": \"meningococcal MCV4P\", "
          + "      \"coding\": [ "
          + "         { "
          + "            \"system\": \"http://hl7.org/fhir/sid/cvx\", "
          + "            \"code\": \"114\" "
          + "         } "
          + "      ] "
          + "   }, "
          + "   \"patient\": { "
          + "      \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "      \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "   }, "
          + "   \"wasNotGiven\": \"false\", "
          + "   \"_reported\": { "
          + "      \"extension\": [ "
          + "         { "
          + "            \"url\": \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", "
          + "            \"valueCode\": \"unsupported\" "
          + "         } "
          + "      ] "
          + "   }, "
          + "   \"reaction\": [ "
          + "      { "
          + "            \"detail\": { "
          + "            \"display\": \"Lethargy\" "
          + "         } "
          + "      } "
          + "   ] "
          + "} ";
  static final String IMMUNIZATION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Immunization\", "
          + "                    \"id\": \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", "
          + "                    \"status\": \"completed\", "
          + "                    \"date\": \"2017-04-24T01:15:52Z\", "
          + "                    \"vaccineCode\": { "
          + "                       \"text\": \"meningococcal MCV4P\", "
          + "                       \"coding\": [ "
          + "                          { "
          + "                             \"system\": \"http://hl7.org/fhir/sid/cvx\", "
          + "                             \"code\": \"114\" "
          + "                          } "
          + "                       ] "
          + "                    }, "
          + "                    \"patient\": { "
          + "                       \"reference\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", "
          + "                       \"display\": \"Mr. Aurelio227 Cruickshank494\" "
          + "                    }, "
          + "                    \"wasNotGiven\": \"false\", "
          + "                    \"_reported\": { "
          + "                       \"extension\": [ "
          + "                          { "
          + "                             \"url\": \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", "
          + "                             \"valueCode\": \"unsupported\" "
          + "                          } "
          + "                       ] "
          + "                    }, "
          + "                    \"reaction\": [ "
          + "                       { "
          + "                           \"detail\": { "
          + "                               \"display\": \"Lethargy\" "
          + "                           } "
          + "                       } "
          + "                    ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String ORGANZIATON =
      "{ "
          + "    \"resourceType\": \"Organization\", "
          + "    \"id\": \"6a96677d-f487-52bb-befd-6c90c7f49fa6\", "
          + "    \"active\": \"true\", "
          + "    \"type\": { "
          + "        \"coding\": [ "
          + "            { "
          + "                \"system\": \"http://hl7.org/fhir/organization-type\", "
          + "                \"code\": \"prov\", "
          + "                \"display\": \"Healthcare Provider\" "
          + "            } "
          + "        ] "
          + "    }, "
          + "    \"name\": \"MANILA-RO\", "
          + "    \"address\": [ "
          + "        { "
          + "            \"line\": [ "
          + "                \"1501 ROXAS BLVD\" "
          + "            ], "
          + "            \"city\": \"PASAY CITY, METRO MANILA\", "
          + "            \"state\": \"PH\", "
          + "            \"postalCode\": \"96515-1100\" "
          + "        } "
          + "    ], "
          + "    \"partOf\": { "
          + "        \"reference\": \"https://api.va.gov/services/argonaut/v0/Organization/966f5985-6db7-5c0a-b809-54fcf73d3e1d\", "
          + "        \"display\": \"VA\" "
          + "    } "
          + "} ";

  static final String ORGANZIATION_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Organization/6a96677d-f487-52bb-befd-6c90c7f49fa6\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Organization/6a96677d-f487-52bb-befd-6c90c7f49fa6\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Organization\", "
          + "                    \"id\": \"6a96677d-f487-52bb-befd-6c90c7f49fa6\", "
          + "                    \"active\": \"true\", "
          + "                    \"type\": { "
          + "                        \"coding\": [ "
          + "                            { "
          + "                                \"system\": \"http://hl7.org/fhir/organization-type\", "
          + "                                \"code\": \"prov\", "
          + "                                \"display\": \"Healthcare Provider\" "
          + "                            } "
          + "                        ] "
          + "                    }, "
          + "                    \"name\": \"MANILA-RO\", "
          + "                    \"address\": [ "
          + "                        { "
          + "                            \"line\": [ "
          + "                                \"1501 ROXAS BLVD\" "
          + "                            ], "
          + "                            \"city\": \"PASAY CITY, METRO MANILA\", "
          + "                            \"state\": \"PH\", "
          + "                            \"postalCode\": \"96515-1100\" "
          + "                        } "
          + "                    ], "
          + "                    \"partOf\": { "
          + "                        \"reference\": \"https://api.va.gov/services/argonaut/v0/Organization/966f5985-6db7-5c0a-b809-54fcf73d3e1d\", "
          + "                        \"display\": \"VA\" "
          + "                    } "
          + "                }, "
          + "            \"search\": { "
          + "                \"mode\": \"match\" "
          + "            } "
          + "        } "
          + "    ] "
          + "} ";

  static final String PATIENT_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", "
          + "                \"resource\": { "
          + "                    \"id\": \"2000163\", "
          + "                    \"resourceType\": \"Patient\", "
          + "                    \"extension\": [ "
          + "                        { "
          + "                            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", "
          + "                            \"extension\": [ "
          + "                                { "
          + "                                    \"url\": \"ombCategory\", "
          + "                                    \"valueCoding\": { "
          + "                                        \"system\": \"http://hl7.org/fhir/v3/Race\", "
          + "                                        \"code\": \"2016-3\", "
          + "                                        \"display\": \"White\" "
          + "                                    } "
          + "                                }, "
          + "                                { "
          + "                                    \"url\": \"text\", "
          + "                                    \"valueString\": \"White\" "
          + "                                } "
          + "                            ] "
          + "                        }, "
          + "                        { "
          + "                            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", "
          + "                            \"extension\": [ "
          + "                                { "
          + "                                    \"url\": \"ombCategory\", "
          + "                                    \"valueCoding\": { "
          + "                                        \"system\": \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", "
          + "                                        \"code\": \"2186-5\", "
          + "                                        \"display\": \"Not Hispanic or Latino\" "
          + "                                    } "
          + "                                }, "
          + "                                { "
          + "                                    \"url\": \"text\", "
          + "                                    \"valueString\": \"Not Hispanic or Latino\" "
          + "                                } "
          + "                            ] "
          + "                        }, "
          + "                        { "
          + "                            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", "
          + "                            \"valueCode\": \"M\" "
          + "                        } "
          + "                    ], "
          + "                    \"identifier\": [ "
          + "                        { "
          + "                            \"use\": \"usual\", "
          + "                            \"type\": { "
          + "                                \"coding\": [ "
          + "                                    { "
          + "                                        \"system\": \"http://hl7.org/fhir/v2/0203\", "
          + "                                        \"code\": \"MR\" "
          + "                                    } "
          + "                                ] "
          + "                            }, "
          + "                            \"system\": \"http://va.gov/mvi\", "
          + "                            \"value\": \"2000163\" "
          + "                        }, "
          + "                        { "
          + "                            \"use\": \"official\", "
          + "                            \"type\": { "
          + "                                \"coding\": [ "
          + "                                    { "
          + "                                        \"system\": \"http://hl7.org/fhir/v2/0203\", "
          + "                                        \"code\": \"SB\" "
          + "                                    } "
          + "                                ] "
          + "                            }, "
          + "                            \"system\": \"http://hl7.org/fhir/sid/us-ssn\", "
          + "                            \"value\": \"999-61-4803\" "
          + "                        } "
          + "                    ], "
          + "                    \"name\": [ "
          + "                        { "
          + "                            \"use\": \"usual\", "
          + "                            \"text\": \"Mr. Aurelio227 Cruickshank494\", "
          + "                            \"family\": [ "
          + "                                \"Cruickshank494\" "
          + "                            ], "
          + "                            \"given\": [ "
          + "                                \"Aurelio227\" "
          + "                            ] "
          + "                        } "
          + "                    ], "
          + "                    \"telecom\": [ "
          + "                        { "
          + "                            \"system\": \"phone\", "
          + "                            \"value\": \"5555191065\", "
          + "                            \"use\": \"mobile\" "
          + "                        }, "
          + "                        { "
          + "                            \"system\": \"email\", "
          + "                            \"value\": \"Aurelio227.Cruickshank494@email.example\" "
          + "                        } "
          + "                    ], "
          + "                    \"gender\": \"male\", "
          + "                    \"birthDate\": \"1995-02-06\", "
          + "                    \"deceasedBoolean\": \"false\", "
          + "                    \"address\": [ "
          + "                        { "
          + "                            \"line\": [ "
          + "                                \"909 Rohan Highlands\" "
          + "                            ], "
          + "                            \"city\": \"Mesa\", "
          + "                            \"state\": \"Arizona\", "
          + "                            \"postalCode\": \"85120\" "
          + "                        } "
          + "                    ], "
          + "                    \"maritalStatus\": { "
          + "                        \"coding\": [ "
          + "                            { "
          + "                                \"system\": \"http://hl7.org/fhir/v3/NullFlavor\", "
          + "                                \"code\": \"UNK\", "
          + "                                \"display\": \"unknown\" "
          + "                            } "
          + "                        ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "            } "
          + "          } "
          + "        } "
          + "    ] "
          + "} ";
  static final String PATIENT =
      "{ "
          + "    \"id\": \"2000163\", "
          + "    \"resourceType\": \"Patient\", "
          + "    \"extension\": [ "
          + "        { "
          + "            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", "
          + "            \"extension\": [ "
          + "                { "
          + "                    \"url\": \"ombCategory\", "
          + "                    \"valueCoding\": { "
          + "                        \"system\": \"http://hl7.org/fhir/v3/Race\", "
          + "                        \"code\": \"2016-3\", "
          + "                        \"display\": \"White\" "
          + "                    } "
          + "                }, "
          + "                { "
          + "                    \"url\": \"text\", "
          + "                    \"valueString\": \"White\" "
          + "                } "
          + "            ] "
          + "        }, "
          + "        { "
          + "            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", "
          + "            \"extension\": [ "
          + "                { "
          + "                    \"url\": \"ombCategory\", "
          + "                    \"valueCoding\": { "
          + "                        \"system\": \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", "
          + "                        \"code\": \"2186-5\", "
          + "                        \"display\": \"Not Hispanic or Latino\" "
          + "                    } "
          + "                }, "
          + "                { "
          + "                    \"url\": \"text\", "
          + "                    \"valueString\": \"Not Hispanic or Latino\" "
          + "                } "
          + "            ] "
          + "        }, "
          + "        { "
          + "            \"url\": \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", "
          + "            \"valueCode\": \"M\" "
          + "        } "
          + "    ], "
          + "    \"identifier\": [ "
          + "        { "
          + "            \"use\": \"usual\", "
          + "            \"type\": { "
          + "                \"coding\": [ "
          + "                    { "
          + "                        \"system\": \"http://hl7.org/fhir/v2/0203\", "
          + "                        \"code\": \"MR\" "
          + "                    } "
          + "                ] "
          + "            }, "
          + "            \"system\": \"http://va.gov/mvi\", "
          + "            \"value\": \"2000163\" "
          + "        }, "
          + "        { "
          + "            \"use\": \"official\", "
          + "            \"type\": { "
          + "                \"coding\": [ "
          + "                    { "
          + "                        \"system\": \"http://hl7.org/fhir/v2/0203\", "
          + "                        \"code\": \"SB\" "
          + "                    } "
          + "                ] "
          + "            }, "
          + "            \"system\": \"http://hl7.org/fhir/sid/us-ssn\", "
          + "            \"value\": \"999-61-4803\" "
          + "        } "
          + "    ], "
          + "    \"name\": [ "
          + "        { "
          + "            \"use\": \"usual\", "
          + "            \"text\": \"Mr. Aurelio227 Cruickshank494\", "
          + "            \"family\": [ "
          + "                \"Cruickshank494\" "
          + "            ], "
          + "            \"given\": [ "
          + "                \"Aurelio227\" "
          + "            ] "
          + "        } "
          + "    ], "
          + "    \"telecom\": [ "
          + "        { "
          + "            \"system\": \"phone\", "
          + "            \"value\": \"5555191065\", "
          + "            \"use\": \"mobile\" "
          + "        }, "
          + "        { "
          + "            \"system\": \"email\", "
          + "            \"value\": \"Aurelio227.Cruickshank494@email.example\" "
          + "        } "
          + "    ], "
          + "    \"gender\": \"male\", "
          + "    \"birthDate\": \"1995-02-06\", "
          + "    \"deceasedBoolean\": \"false\", "
          + "    \"address\": [ "
          + "        { "
          + "            \"line\": [ "
          + "                \"909 Rohan Highlands\" "
          + "            ], "
          + "            \"city\": \"Mesa\", "
          + "            \"state\": \"Arizona\", "
          + "            \"postalCode\": \"85120\" "
          + "        } "
          + "    ], "
          + "    \"maritalStatus\": { "
          + "        \"coding\": [ "
          + "            { "
          + "                \"system\": \"http://hl7.org/fhir/v3/NullFlavor\", "
          + "                \"code\": \"UNK\", "
          + "                \"display\": \"unknown\" "
          + "            } "
          + "        ] "
          + "    } "
          + "} ";

  static final String PRACTITIONER =
      "{ "
          + "    \"resourceType\": \"Practitioner\", "
          + "    \"id\": \"9e8531cb-8069-5328-b737-938fa044a4e2\", "
          + "    \"active\": \"true\", "
          + "    \"name\": { "
          + "        \"use\": \"usual\", "
          + "        \"text\": \"CARUNGIN,CHAD REY V\", "
          + "        \"family\": [ "
          + "            \"CARUNGIN\" "
          + "        ], "
          + "        \"given\": [ "
          + "            \"CHAD REY\" "
          + "        ], "
          + "        \"suffix\": [ "
          + "            \"V\" "
          + "        ] "
          + "    }, "
          + "    \"telecom\": [ "
          + "        { "
          + "            \"system\": \"phone\", "
          + "            \"value\": \"318-8387\", "
          + "            \"use\": \"work\" "
          + "        }, "
          + "        { "
          + "            \"system\": \"phone\", "
          + "            \"value\": \"638334566\", "
          + "            \"use\": \"home\" "
          + "        } "
          + "    ], "
          + "    \"gender\": \"male\", "
          + "    \"birthDate\": \"1964-02-16\", "
          + "    \"practitionerRole\": [ "
          + "        { "
          + "            \"managingOrganization\": { "
          + "                \"reference\": \"https://api.va.gov/services/argonaut/v0/Organization/a29c7d77-fbae-5852-a905-1b18385b0339\", "
          + "                \"display\": \"MANILA-RO\" "
          + "            }, "
          + "            \"role\": { "
          + "                \"coding\": [ "
          + "                    { "
          + "                        \"system\": \"http://hl7.org/fhir/practitioner-role\", "
          + "                        \"code\": \"doctor\", "
          + "                        \"display\": \"Doctor\" "
          + "                    } "
          + "                ] "
          + "            }, "
          + "            \"location\": [ "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/fb2a6389-0512-5ed1-9b49-811d5f3fdf3d\", "
          + "                    \"display\": \"PULMO CONSULT\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/be4abb7c-87ea-57de-9347-df849897ea28\", "
          + "                    \"display\": \"ZZORANGE\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/c7c5e616-4304-5956-804f-36038889f712\", "
          + "                    \"display\": \"ZZZ MAN PACT ORANGE\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/2a560bee-9f00-5758-aaa3-21c0f929a7f6\", "
          + "                    \"display\": \"ZZORANGE INTERNAL MED CLINIC\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/ada6bbf5-f121-582e-b832-13387fe4feff\", "
          + "                    \"display\": \"MAN PACT WALK-IN\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/d05e1bc2-9527-51e9-bc35-0132f2af3c53\", "
          + "                    \"display\": \"E-CONSULT PULMO\" "
          + "                }, "
          + "                { "
          + "                    \"reference\": https://api.va.gov/services/argonaut/v0/Location/1cdb2958-e0fb-5711-8907-d582662e1be7, "
          + "                    \"display\": MNL-SECMSG-PULMO "
          + "                } "
          + "            ], "
          + "            healthcareService: [ "
          + "                { "
          + "                    \"display\": \"PROFESSIONAL SERVICES DIVISION\" "
          + "                } "
          + "            ] "
          + "        } "
          + "    ] "
          + "} ";

  static final String PRACTITIONER_BUNDLE =
      "{ "
          + "    \"resourceType\": \"Bundle\", "
          + "    \"type\": \"searchset\", "
          + "    \"total\": 1, "
          + "    \"link\": [ "
          + "        { "
          + "            \"relation\": \"self\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\": \"first\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" "
          + "        }, "
          + "        { "
          + "            \"relation\":\"last\", "
          + "            \"url\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" "
          + "        } "
          + "    ], "
          + "    \"entry\": [ "
          + "        { "
          + "            \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/9e8531cb-8069-5328-b737-938fa044a4e2\", "
          + "            \"resource\": { "
          + "                \"fullUrl\": \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/9e8531cb-8069-5328-b737-938fa044a4e2\", "
          + "                \"resource\": { "
          + "                    \"resourceType\": \"Practitioner\", "
          + "                    \"id\": \"9e8531cb-8069-5328-b737-938fa044a4e2\", "
          + "                    \"active\": \"true\", "
          + "                    \"name\": { "
          + "                        \"use\": \"usual\", "
          + "                        \"text\": \"CARUNGIN,CHAD REY V\", "
          + "                        \"family\": [ "
          + "                            \"CARUNGIN\" "
          + "                        ], "
          + "                        \"given\": [ "
          + "                            \"CHAD REY\" "
          + "                        ], "
          + "                        \"suffix\": [ "
          + "                            \"V\" "
          + "                        ] "
          + "                    }, "
          + "                    \"telecom\": [ "
          + "                        { "
          + "                            \"system\": \"phone\", "
          + "                            \"value\": \"318-8387\", "
          + "                            \"use\": \"work\" "
          + "                        }, "
          + "                        { "
          + "                            \"system\": \"phone\", "
          + "                            \"value\": \"638334566\", "
          + "                            \"use\": \"home\" "
          + "                        } "
          + "                    ], "
          + "                    \"gender\": \"male\", "
          + "                    \"birthDate\": \"1964-02-16\", "
          + "                    \"practitionerRole\": [ "
          + "                        { "
          + "                            \"managingOrganization\": { "
          + "                                \"reference\": \"https://api.va.gov/services/argonaut/v0/Organization/a29c7d77-fbae-5852-a905-1b18385b0339\", "
          + "                                \"display\": \"MANILA-RO\" "
          + "                            }, "
          + "                            \"role\": { "
          + "                                \"coding\": [ "
          + "                                    { "
          + "                                        \"system\": \"http://hl7.org/fhir/practitioner-role\", "
          + "                                        \"code\": \"doctor\", "
          + "                                        \"display\": \"Doctor\" "
          + "                                    } "
          + "                                ] "
          + "                            }, "
          + "                            \"location\": [ "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/fb2a6389-0512-5ed1-9b49-811d5f3fdf3d\", "
          + "                                    \"display\": \"PULMO CONSULT\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/be4abb7c-87ea-57de-9347-df849897ea28\", "
          + "                                    \"display\": \"ZZORANGE\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/c7c5e616-4304-5956-804f-36038889f712\", "
          + "                                    \"display\": \"ZZZ MAN PACT ORANGE\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/2a560bee-9f00-5758-aaa3-21c0f929a7f6\", "
          + "                                    \"display\": \"ZZORANGE INTERNAL MED CLINIC\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/ada6bbf5-f121-582e-b832-13387fe4feff\", "
          + "                                    \"display\": \"MAN PACT WALK-IN\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": \"https://api.va.gov/services/argonaut/v0/Location/d05e1bc2-9527-51e9-bc35-0132f2af3c53\", "
          + "                                    \"display\": \"E-CONSULT PULMO\" "
          + "                                }, "
          + "                                { "
          + "                                    \"reference\": https://api.va.gov/services/argonaut/v0/Location/1cdb2958-e0fb-5711-8907-d582662e1be7, "
          + "                                   \"display\": MNL-SECMSG-PULMO "
          + "                                } "
          + "                            ], "
          + "                            healthcareService: [ "
          + "                                { "
          + "                                    \"display\": \"PROFESSIONAL SERVICES DIVISION\" "
          + "                                } "
          + "                            ] "
          + "                        } "
          + "                    ] "
          + "                }, "
          + "                \"search\": { "
          + "                    \"mode\": \"match\" "
          + "                } "
          + "        } "
          + "    ] "
          + "} ";
}
