package gov.va.api.health.argonaut.api.resources;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/** Samples for swagger documentation. */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
class SwaggerExamples {

  static final String ALLERGY_INTOLERANCE =
      "{ \n"
          + "    resourceType: \"AllergyIntolerance\", \n"
          + "    id: \"6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", \n"
          + "    onset: \"1995-04-30T01:15:52Z\", \n"
          + "    patient: { \n"
          + "       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "    }, \n"
          + "    substance: { \n"
          + "        text: \"Allergy to peanuts\" \n"
          + "   }, \n"
          + "    status: \"active\", \n"
          + "    type: \"allergy\", \n"
          + "    category: \"food\", \n"
          + "    note: { \n"
          + "        time: \"1995-04-30T01:15:52Z\", \n"
          + "        text: \"Allergy to peanuts\" \n"
          + "    }, \n"
          + "    reaction: [ \n"
          + "        { \n"
          + "            manifestation: [ \n"
          + "                { \n"
          + "                    coding: [ \n"
          + "                        { \n"
          + "                            display: \"Inflammation of Skin\", \n"
          + "                            system: \"urn:oid:2.16.840.1.113883.6.233\", \n"
          + "                            code: \"2000001\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    text: \"Inflammation of Skin\" \n"
          + "                } \n"
          + "            ], \n"
          + "            certainty: \"likely\" \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String ALLERGY_INTOLERANCE_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/6f9a021b-07d5-53c8-8cce-b49a694d4ad9\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/AllergyIntolerance/e2019e0c-fa38-596d-b966-9b86926959a7\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"AllergyIntolerance\", \n"
          + "                    id: \"e2019e0c-fa38-596d-b966-9b86926959a7\", \n"
          + "                    onset: \"1995-04-30T01:15:52Z\", \n"
          + "                    patient: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    substance: { \n"
          + "                        text: \"Allergy to bee venom\" \n"
          + "                    }, \n"
          + "                    status: \"active\", \n"
          + "                    type: \"allergy\", \n"
          + "                    note: { \n"
          + "                        time: \"1995-04-30T01:15:52Z\", \n"
          + "                        text: \"Allergy to bee venom\" \n"
          + "                    }, \n"
          + "                    reaction: [ \n"
          + "                        { \n"
          + "                            manifestation: [ \n"
          + "                                { \n"
          + "                                    coding: [ \n"
          + "                                        { \n"
          + "                                            display: \"Sneezing and Coughing\", \n"
          + "                                            system: \"urn:oid:2.16.840.1.233\", \n"
          + "                                            code: \"2000004\" \n"
          + "                                        } \n"
          + "                                    ], \n"
          + "                                    text: \"Sneezing and Coughing\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String APPOINTMENT =
      " { \n"
          + "   resourceType: \"Appointment\", \n"
          + "   id: \"0be173b4-721c-554e-ba7d-966d04633b68\", \n"
          + "   status: \"cancelled\", \n"
          + "   description: \"Scheduled Visit\", \n"
          + "   start: \"2006-06-30T17:00:00Z\", \n"
          + "   participant: [ \n"
          + "     { \n"
          + "       type: [ \n"
          + "         { \n"
          + "           system: \"http://hl7.org/fhir/v3/ParticipationType\", \n"
          + "           code: \"PART\", \n"
          + "           display: \"Participation\" \n"
          + "         } \n"
          + "       ], \n"
          + "       actor: { \n"
          + "         reference: \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", \n"
          + "         display: \"VETERAN,JOHN Q\" \n"
          + "       }, \n"
          + "       required: \"required\", \n"
          + "       status: \"accepted\" \n"
          + "     }, \n"
          + "     { \n"
          + "       type: [ \n"
          + "         { \n"
          + "           system: \"http://hl7.org/fhir/v3/ParticipationType\", \n"
          + "           code: \"PART\", \n"
          + "           display: \"Participation\" \n"
          + "         } \n"
          + "       ], \n"
          + "       actor: { \n"
          + "         reference: \"https://www.freedomstream.io/Argonaut/api/Location/71fed7fc-d060-5a35-bba9-e89fd7cdb4e6\", \n"
          + "         display: \"ZZZTG SURG POD SCHEULLER COBI\" \n"
          + "       }, \n"
          + "       required: \"required\", \n"
          + "       status: \"accepted\" \n"
          + "     } \n"
          + "   ] \n"
          + " } ";

  static final String APPOINTMENT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Appointment?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Appointment/0be173b4-721c-554e-ba7d-966d04633b68\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Appointment/0be173b4-721c-554e-ba7d-966d04633b68\", \n"
          + "                resource: { \n"
          + "                      resourceType: \"Appointment\", \n"
          + "                      id: \"0be173b4-721c-554e-ba7d-966d04633b68\", \n"
          + "                      status: \"cancelled\", \n"
          + "                      description: \"Scheduled Visit\", \n"
          + "                      start: \"2006-06-30T17:00:00Z\", \n"
          + "                      participant: [ \n"
          + "                        { \n"
          + "                          type: [ \n"
          + "                            { \n"
          + "                              system: \"http://hl7.org/fhir/v3/ParticipationType\", \n"
          + "                              code: \"PART\", \n"
          + "                              display: \"Participation\" \n"
          + "                            } \n"
          + "                          ], \n"
          + "                          actor: { \n"
          + "                            reference: \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", \n"
          + "                            display: \"VETERAN,JOHN Q\" \n"
          + "                          }, \n"
          + "                          required: \"required\", \n"
          + "                          status: \"accepted\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                          type: [ \n"
          + "                            { \n"
          + "                              system: \"http://hl7.org/fhir/v3/ParticipationType\", \n"
          + "                              code: \"PART\", \n"
          + "                              display: \"Participation\" \n"
          + "                            } \n"
          + "                          ], \n"
          + "                          actor: { \n"
          + "                            reference: \"https://www.freedomstream.io/Argonaut/api/Location/71fed7fc-d060-5a35-bba9-e89fd7cdb4e6\", \n"
          + "                            display: \"ZZZTG SURG POD SCHEULLER COBI\" \n"
          + "                          }, \n"
          + "                          required: \"required\", \n"
          + "                          status: \"accepted\" \n"
          + "                        } \n"
          + "                      ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String CONDITION =
      "{ \n"
          + "    resourceType: \"Condition\", \n"
          + "    id: \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "    patient: { \n"
          + "        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "    }, \n"
          + "    code: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                code: \"38341003\", \n"
          + "                system: \"https://www.snomed.org/snomed-ct\", \n"
          + "                display: \"Hypertension\" \n"
          + "            } \n"
          + "        ], \n"
          + "        text: \"Hypertension\" \n"
          + "    }, \n"
          + "    category: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"http://argonaut.hl7.org\", \n"
          + "                code: \"problem\" \n"
          + "            } \n"
          + "        ] \n"
          + "    }, \n"
          + "    clinicalStatus: \"active\", \n"
          + "    verificationStatus: \"unknown\", \n"
          + "    dateRecorded: \"2013-04-14\", \n"
          + "    onsetDateTime: \"2013-04-15T01:15:52Z\" \n"
          + "} ";
  static final String CONDITION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Condition?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Condition/b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Condition\", \n"
          + "                    id: \"b34bacd3-42b6-5613-b1c2-1abafe1248ba\", \n"
          + "                    patient: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                        coding: [ \n"
          + "                           { \n"
          + "                               code: \"38341003\", \n"
          + "                               system: \"https://www.snomed.org/snomed-ct\", \n"
          + "                               display: \"Hypertension\" \n"
          + "                           } \n"
          + "                        ], \n"
          + "                        text: \"Hypertension\" \n"
          + "                    }, \n"
          + "                    category: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://argonaut.hl7.org\", \n"
          + "                                code: \"problem\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    clinicalStatus: \"active\", \n"
          + "                    verificationStatus: \"unknown\", \n"
          + "                    dateRecorded: \"2013-04-14\", \n"
          + "                    onsetDateTime: \"2013-04-15T01:15:52Z\" \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String ENCOUNTER =
      "{ \n"
          + "  resourceType: \"Encounter\", \n"
          + "  id: \"dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", \n"
          + "  status: \"finished\", \n"
          + "  class: \"emergency\", \n"
          + "  patient: { \n"
          + "    reference: \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", \n"
          + "    display: \"VETERAN,JOHN Q\" \n"
          + "  }, \n"
          + "  participant: [ \n"
          + "    { \n"
          + "      individual: { \n"
          + "        reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/d3f56fac-c7c7-547b-a1e9-de3173d4b628\", \n"
          + "        display: \"CARTER,DOC F\" \n"
          + "      } \n"
          + "    }, \n"
          + "    { \n"
          + "      individual: { \n"
          + "        reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/93e4e3c3-8d8c-5b53-996f-6047d0232231\", \n"
          + "        display: \"JONES,DOC B \n"
          + "      } \n"
          + "    }, \n"
          + "    { \n"
          + "      individual: { \n"
          + "        reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/5e27c469-82e4-5725-babb-49cf7eee948f\", \n"
          + "        display: CARTER,DOC F\" \n"
          + "      } \n"
          + "    }, \n"
          + "    { \n"
          + "      individual: { \n"
          + "        reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/1b489f04-19e7-5c7d-9140-ce773c158edd\", \n"
          + "        display: \"SMITH,DOC A\" \n"
          + "      } \n"
          + "    } \n"
          + "  ], \n"
          + "  appointment: { \n"
          + "    reference: \"https://www.freedomstream.io/Argonaut/api/Appointment/615f31df-f0c7-5100-ac42-7fb952c630d0\" \n"
          + "  }, \n"
          + "  indication: [ \n"
          + "    { \n"
          + "      reference: \"https://www.freedomstream.io/Argonaut/api/Condition/37d89dc5-45f5-5a2e-9db9-2b17c0d7f318\", \n"
          + "      display: \"Chronic asthmatic bronchitis (SNOMED CT 195949008)\" \n"
          + "    } \n"
          + "  ], \n"
          + "  location: [ \n"
          + "    { \n"
          + "      location: { \n"
          + "        reference: \"https://www.freedomstream.io/Argonaut/api/Location/eb094a51-ad31-5b6b-b627-96aac4b02b1c\", \n"
          + "        display: \"GNV ED\" \n"
          + "      } \n"
          + "    } \n"
          + "  ], \n"
          + "  serviceProvider: { \n"
          + "    reference: \"https://www.freedomstream.io/Argonaut/api/Institution/ed3f9a41-397a-5100-b177-ae3815e5c370\", \n"
          + "    display: \"N. FLORIDA/S. GEORGIA HCS\" \n"
          + "  } \n"
          + "} ";

  static final String ENCOUNTER_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Encounter?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Encounter/dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Encounter/dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", \n"
          + "                resource: { \n"
          + "                   resourceType: \"Encounter\", \n"
          + "                   id: \"dc7f6fcc-41f9-5be9-a364-0b0aa938917a\", \n"
          + "                   status: \"finished\", \n"
          + "                   class: \"emergency\", \n"
          + "                   patient: { \n"
          + "                     reference: \"https://www.freedomstream.io/Argonaut/api/Patient/185601V825290\", \n"
          + "                     display: \"VETERAN,JOHN Q\" \n"
          + "                   }, \n"
          + "                   participant: [ \n"
          + "                     { \n"
          + "                       individual: { \n"
          + "                         reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/d3f56fac-c7c7-547b-a1e9-de3173d4b628\", \n"
          + "                         display: \"CARTER,DOC F\" \n"
          + "                       } \n"
          + "                     }, \n"
          + "                     { \n"
          + "                       individual: { \n"
          + "                         reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/93e4e3c3-8d8c-5b53-996f-6047d0232231\", \n"
          + "                         display: \"JONES,DOC B \n"
          + "                       } \n"
          + "                     }, \n"
          + "                     { \n"
          + "                       individual: { \n"
          + "                         reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/5e27c469-82e4-5725-babb-49cf7eee948f\", \n"
          + "                         display: CARTER,DOC F\" \n"
          + "                       } \n"
          + "                     }, \n"
          + "                     { \n"
          + "                       individual: { \n"
          + "                         reference: \"https://www.freedomstream.io/Argonaut/api/Practitioner/1b489f04-19e7-5c7d-9140-ce773c158edd\", \n"
          + "                         display: \"SMITH,DOC A\" \n"
          + "                       } \n"
          + "                     } \n"
          + "                   ], \n"
          + "                   appointment: { \n"
          + "                     reference: \"https://www.freedomstream.io/Argonaut/api/Appointment/615f31df-f0c7-5100-ac42-7fb952c630d0\" \n"
          + "                   }, \n"
          + "                   indication: [ \n"
          + "                     { \n"
          + "                       reference: \"https://www.freedomstream.io/Argonaut/api/Condition/37d89dc5-45f5-5a2e-9db9-2b17c0d7f318\", \n"
          + "                       display: \"Chronic asthmatic bronchitis (SNOMED CT 195949008)\" \n"
          + "                     } \n"
          + "                   ], \n"
          + "                   location: [ \n"
          + "                     { \n"
          + "                       location: { \n"
          + "                         reference: \"https://www.freedomstream.io/Argonaut/api/Location/eb094a51-ad31-5b6b-b627-96aac4b02b1c\", \n"
          + "                         display: \"GNV ED\" \n"
          + "                       } \n"
          + "                     } \n"
          + "                   ], \n"
          + "                   serviceProvider: { \n"
          + "                     reference: \"https://www.freedomstream.io/Argonaut/api/Institution/ed3f9a41-397a-5100-b177-ae3815e5c370\", \n"
          + "                     display: \"N. FLORIDA/S. GEORGIA HCS\" \n"
          + "                   } \n"
          + "            }, \n"
          + "            search: { \n"
          + "                mode: \"match\" \n"
          + "            } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String LOCATION =
      "{ \n"
          + "  resourceType: \"Location\", \n"
          + "  id: \"96aee2f5-a2ce-588f-8352-f6ea61f0959d\", \n"
          + "  status: \"active\", \n"
          + "  name: \"VAMC ALBANY\", \n"
          + "  description: \"VAMC ALBANY\", \n"
          + "  mode: \"instance\", \n"
          + "  address: { \n"
          + "    line: [ \n"
          + "      \"113 Holland Avenue\" \n"
          + "    ], \n"
          + "    city: \"ALBANY\", \n"
          + "    state: \"NEW YORK\" \n"
          + "  }, \n"
          + "  managingOrganization: { \n"
          + "    reference: \"https://www.freedomstream.io/Argonaut/api/Organization/e207c621-f467-5983-a6d1-868f33cefa95\", \n"
          + "    display: \"ZZ ALBANY\" \n"
          + "  } \n"
          + "} ";

  static final String LOCATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Location?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Location/96aee2f5-a2ce-588f-8352-f6ea61f0959d\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Location/96aee2f5-a2ce-588f-8352-f6ea61f0959d\", \n"
          + "                resource: { \n"
          + "                  resourceType: \"Location\", \n"
          + "                  id: \"96aee2f5-a2ce-588f-8352-f6ea61f0959d\", \n"
          + "                  status: \"active\", \n"
          + "                  name: \"VAMC ALBANY\", \n"
          + "                  description: \"VAMC ALBANY\", \n"
          + "                  mode: \"instance\", \n"
          + "                  address: { \n"
          + "                    line: [ \n"
          + "                      \"113 Holland Avenue\" \n"
          + "                    ], \n"
          + "                    city: \"ALBANY\", \n"
          + "                    state: \"NEW YORK\" \n"
          + "                  }, \n"
          + "                  managingOrganization: { \n"
          + "                    reference: \"https://www.freedomstream.io/Argonaut/api/Organization/e207c621-f467-5983-a6d1-868f33cefa95\", \n"
          + "                    display: \"ZZ ALBANY\" \n"
          + "                  } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String OPERATION_OUTCOME =
      "{ \n"
          + "    resourceType: \"OperationOutcome\", \n"
          + "    issue: [ \n"
          + "        { \n"
          + "            severity: \"error\", \n"
          + "            code: \"forbidden\", \n"
          + "            details: { \n"
          + "                text: \"Token not allowed access to this patient.\" \n"
          + "            } \n"
          + "        } \n"
          + "    ] \n"
          + "} \n";

  static final String MEDICATION =
      "{ \n"
          + "    resourceType: \"Medication\", \n"
          + "    id: \"f4163f35-1565-552b-a1b9-a2f8870e6f4a\", \n"
          + "    code: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"https://www.nlm.nih.gov/research/umls/rxnorm/\", \n"
          + "                code: \"895994\", \n"
          + "                display: \"120 Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "            } \n"
          + "        ], \n"
          + "        text: \"120 ACTUAT Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "    }, \n"
          + "    product: { \n"
          + "        id: \"4024655\", \n"
          + "        form: { \n"
          + "            text: \"1 dose(s) 1 time(s) per 1 days\" \n"
          + "        } \n"
          + "    } \n"
          + "} ";

  static final String MEDICATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Medication?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Medication/f4163f35-1565-552b-a1b9-a2f8870e6f4a\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Medication/f4163f35-1565-552b-a1b9-a2f8870e6f4a\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Medication\", \n"
          + "                    id: \"f4163f35-1565-552b-a1b9-a2f8870e6f4a\", \n"
          + "                    code: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"https://www.nlm.nih.gov/research/umls/rxnorm/\", \n"
          + "                                code: \"895994\", \n"
          + "                                display: \"120 Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "                            } \n"
          + "                        ], \n"
          + "                        text: \"120 ACTUAT Fluticasone propionate .044 MG/ACTUAT Inhaler\" \n"
          + "                    }, \n"
          + "                    product: { \n"
          + "                        id: \"4024655\", \n"
          + "                        form: { \n"
          + "                            text: \"1 dose(s) 1 time(s) per 1 days\" \n"
          + "                        } \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String PROCEDURE =
      "{ \n"
          + "   resourceType: \"Procedure\", \n"
          + "   id: \"532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "   subject: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   status: \"completed\", \n"
          + "   code: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            display: \"Documentation of current medications\", \n"
          + "            system: \"http://www.ama-assn.org/go/cpt\", \n"
          + "            code: \"XXXXX\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   notPerformed: \"false\", \n"
          + "   performedDateTime: \"2017-04-24T01:15:52Z\" \n"
          + "} ";
  static final String PROCEDURE_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Procedure?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Procedure/532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Procedure\", \n"
          + "                    id: \"532070f1-cb7b-582e-9380-9e0ef27bc817\", \n"
          + "                    subject: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    status: \"completed\", \n"
          + "                    code: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             display: \"Documentation of current medications\", \n"
          + "                             system: \"http://www.ama-assn.org/go/cpt\", \n"
          + "                             code: \"XXXXX\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    notPerformed: \"false\", \n"
          + "                    performedDateTime: \"2017-04-24T01:15:52Z\" \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String OBSERVATION =
      "{ \n"
          + "   resourceType: \"Observation\", \n"
          + "   id: \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "   status: \"final\", \n"
          + "   category: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/observation-category\", \n"
          + "            code: \"laboratory\", \n"
          + "            display: \"Laboratory\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   code: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://loinc.org\", \n"
          + "            code: \"32623-1\", \n"
          + "            display: \"Platelet mean volume [Entitic volume] in Blood by \" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   subject\": { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   effectiveDateTime: \"2017-04-24T01:15:52Z\", \n"
          + "   issued: \"2017-04-24T01:15:52Z\", \n"
          + "   valueQuantity: { \n"
          + "      value: 10.226877417360429, \n"
          + "      unit: \"fL\", \n"
          + "      system: \"http://unitsofmeasure.org\", \n"
          + "      code: \"fL\" \n"
          + "   } \n"
          + "} ";
  static final String OBSERVATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Observation?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Observation/7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Observation\", \n"
          + "                    id: \"7889e577-88d6-5e6f-8a4d-fb6988b7b3c1\", \n"
          + "                    status: \"final\", \n"
          + "                    category: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://hl7.org/fhir/observation-category\", \n"
          + "                             code: \"laboratory\", \n"
          + "                             display: \"Laboratory\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://loinc.org\", \n"
          + "                             code: \"32623-1\", \n"
          + "                             display: \"Platelet mean volume in Blood by \" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    subject\": { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    effectiveDateTime: \"2017-04-24T01:15:52Z\", \n"
          + "                    issued: \"2017-04-24T01:15:52Z\", \n"
          + "                    valueQuantity: { \n"
          + "                       value: 10.226877417360429, \n"
          + "                       unit: \"fL\", \n"
          + "                       system: \"http://unitsofmeasure.org\", \n"
          + "                       code: \"fL\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String MEDICATION_STATEMENT =
      "{ \n"
          + "   resourceType: \"MedicationStatement\", \n"
          + "   id: \"1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   dateAsserted: \"2013-04-15T01:15:52Z\", \n"
          + "   status: \"active\", \n"
          + "   medicationReference: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "      display: \"Hydrochlorothiazide 25 MG\" \n"
          + "   }, \n"
          + "   dosage: [ \n"
          + "      { \n"
          + "         text: \"Once per day.\", \n"
          + "         timing: { \n"
          + "            code: { \n"
          + "               text: \"As directed by physician.\" \n"
          + "            } \n"
          + "         }, \n"
          + "         route: { \n"
          + "            text: \"As directed by physician.\" \n"
          + "         } \n"
          + "      } \n"
          + "   ] \n"
          + "} ";
  static final String MEDICATION_STATEMENT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationStatement/1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"MedicationStatement\", \n"
          + "                    id: \"1f46363d-af9b-5ba5-acda-b384373a9af2\", \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    dateAsserted: \"2013-04-15T01:15:52Z\", \n"
          + "                    status: \"active\", \n"
          + "                    medicationReference: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "                       display: \"Hydrochlorothiazide 25 MG\" \n"
          + "                    }, \n"
          + "                    dosage: [ \n"
          + "                       { \n"
          + "                          text: \"Once per day.\", \n"
          + "                          timing: { \n"
          + "                             code: { \n"
          + "                                text: \"As directed by physician.\" \n"
          + "                             } \n"
          + "                          }, \n"
          + "                          route: { \n"
          + "                             text: \"As directed by physician.\" \n"
          + "                          } \n"
          + "                       } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String MEDICATION_ORDER =
      "{ \n"
          + "   resourceType: \"MedicationOrder\", \n"
          + "   id: \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "   dateWritten: \"2013-04-14T06:00:00Z\", \n"
          + "   status: \"active\", \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   _prescriber: { \n"
          + "       extension: [ \n"
          + "           { \n"
          + "               url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "               valueCode: \"unsupported\" \n"
          + "           } \n"
          + "       ] \n"
          + "   }, \n"
          + "   medicationReference: { \n"
          + "       reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "       display: \"Hydrochlorothiazide 25 MG\" \n"
          + "   } \n"
          + "} ";
  static final String MEDICATION_ORDER_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/MedicationOrder/f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"MedicationOrder\", \n"
          + "                    id: \"f07dd74e-844e-5463-99d4-0ca4d5cbeb41\", \n"
          + "                    dateWritten: \"2013-04-14T06:00:00Z\", \n"
          + "                    status: \"active\", \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    _prescriber: { \n"
          + "                        extension: [ \n"
          + "                            { \n"
          + "                                url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "                                valueCode: \"unsupported\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    medicationReference: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Medication/7b550d7f-2db8-5002-bc0c-150a70d02944\", \n"
          + "                        display: \"Hydrochlorothiazide 25 MG\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String DIAGNOSTIC_REPORT =
      "{ \n"
          + "   resourceType: \"DiagnosticReport\", \n"
          + "   id: \"0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "   status: \"final\", \n"
          + "   category: { \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", \n"
          + "            code: \"LAB\", \n"
          + "            display: \"Laboratory\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   code: { \n"
          + "      text: \"panel\" \n"
          + "   }, \n"
          + "   effectiveDateTime: \"2011-04-04T01:15:52Z\", \n"
          + "   issued: \"2011-04-04T01:15:52Z\", \n"
          + "   subject: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   } \n"
          + "} ";
  static final String DIAGNOSTIC_REPORT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/DiagnosticReport/0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"DiagnosticReport\", \n"
          + "                    id: \"0757389a-6e06-51bd-aac0-bd0244e51e46\", \n"
          + "                    status: \"final\", \n"
          + "                    category: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://hl7.org/fhir/ValueSet/diagnostic-service-sections\", \n"
          + "                                code: \"LAB\", \n"
          + "                                display: \"Laboratory\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    code: { \n"
          + "                        text: \"panel\" \n"
          + "                    }, \n"
          + "                    effectiveDateTime: \"2011-04-04T01:15:52Z\", \n"
          + "                    issued: \"2011-04-04T01:15:52Z\", \n"
          + "                    subject: { \n"
          + "                        reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                        display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String IMMUNIZATION =
      "{ \n"
          + "   resourceType: \"Immunization\", \n"
          + "   id: \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "   status: \"completed\", \n"
          + "   date: \"2017-04-24T01:15:52Z\", \n"
          + "   vaccineCode: { \n"
          + "      text: \"meningococcal MCV4P\", \n"
          + "      coding: [ \n"
          + "         { \n"
          + "            system: \"http://hl7.org/fhir/sid/cvx\", \n"
          + "            code: \"114\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   patient: { \n"
          + "      reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "      display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "   }, \n"
          + "   wasNotGiven: \"false\", \n"
          + "   _reported: { \n"
          + "      extension: [ \n"
          + "         { \n"
          + "            url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "            valueCode: \"unsupported\" \n"
          + "         } \n"
          + "      ] \n"
          + "   }, \n"
          + "   reaction: [ \n"
          + "      { \n"
          + "            detail: { \n"
          + "            display: \"Lethargy\" \n"
          + "         } \n"
          + "      } \n"
          + "   ] \n"
          + "} ";
  static final String IMMUNIZATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Immunization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Immunization/1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Immunization\", \n"
          + "                    id: \"1fd82e3a-a95b-5c04-9a68-c8ddf740ea0c\", \n"
          + "                    status: \"completed\", \n"
          + "                    date: \"2017-04-24T01:15:52Z\", \n"
          + "                    vaccineCode: { \n"
          + "                       text: \"meningococcal MCV4P\", \n"
          + "                       coding: [ \n"
          + "                          { \n"
          + "                             system: \"http://hl7.org/fhir/sid/cvx\", \n"
          + "                             code: \"114\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    patient: { \n"
          + "                       reference: \"https://dev-api.va.gov/services/argonaut/v0/Patient/2000163\", \n"
          + "                       display: \"Mr. Aurelio227 Cruickshank494\" \n"
          + "                    }, \n"
          + "                    wasNotGiven: \"false\", \n"
          + "                    _reported: { \n"
          + "                       extension: [ \n"
          + "                          { \n"
          + "                             url: \"http://hl7.org/fhir/StructureDefinition/data-absent-reason\", \n"
          + "                             valueCode: \"unsupported\" \n"
          + "                          } \n"
          + "                       ] \n"
          + "                    }, \n"
          + "                    reaction: [ \n"
          + "                       { \n"
          + "                           detail: { \n"
          + "                               display: \"Lethargy\" \n"
          + "                           } \n"
          + "                       } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String ORGANZIATON =
      "{ \n"
          + "    resourceType: \"Organization\", \n"
          + "    id: \"6a96677d-f487-52bb-befd-6c90c7f49fa6\", \n"
          + "    active: \"true\", \n"
          + "    type: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"http://hl7.org/fhir/organization-type\", \n"
          + "                code: \"prov\", \n"
          + "                display: \"Healthcare Provider\" \n"
          + "            } \n"
          + "        ] \n"
          + "    }, \n"
          + "    name: \"MANILA-RO\", \n"
          + "    address: [ \n"
          + "        { \n"
          + "            line: [ \n"
          + "                \"1501 ROXAS BLVD\" \n"
          + "            ], \n"
          + "            city: \"PASAY CITY, METRO MANILA\", \n"
          + "            state: \"PH\", \n"
          + "            postalCode: \"96515-1100\" \n"
          + "        } \n"
          + "    ], \n"
          + "    partOf: { \n"
          + "        reference: \"https://api.va.gov/services/argonaut/v0/Organization/966f5985-6db7-5c0a-b809-54fcf73d3e1d\", \n"
          + "        display: \"VA\" \n"
          + "    } \n"
          + "} ";

  static final String ORGANZIATION_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Organization?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Organization/6a96677d-f487-52bb-befd-6c90c7f49fa6\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Organization/6a96677d-f487-52bb-befd-6c90c7f49fa6\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Organization\", \n"
          + "                    id: \"6a96677d-f487-52bb-befd-6c90c7f49fa6\", \n"
          + "                    active: \"true\", \n"
          + "                    type: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://hl7.org/fhir/organization-type\", \n"
          + "                                code: \"prov\", \n"
          + "                                display: \"Healthcare Provider\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    name: \"MANILA-RO\", \n"
          + "                    address: [ \n"
          + "                        { \n"
          + "                            line: [ \n"
          + "                                \"1501 ROXAS BLVD\" \n"
          + "                            ], \n"
          + "                            city: \"PASAY CITY, METRO MANILA\", \n"
          + "                            state: \"PH\", \n"
          + "                            postalCode: \"96515-1100\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    partOf: { \n"
          + "                        reference: \"https://api.va.gov/services/argonaut/v0/Organization/966f5985-6db7-5c0a-b809-54fcf73d3e1d\", \n"
          + "                        display: \"VA\" \n"
          + "                    } \n"
          + "                }, \n"
          + "            search: { \n"
          + "                mode: \"match\" \n"
          + "            } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String PATIENT_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Patient?_id=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Patient/1017283148V813263\", \n"
          + "                resource: { \n"
          + "                    id: \"2000163\", \n"
          + "                    resourceType: \"Patient\", \n"
          + "                    extension: [ \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", \n"
          + "                            extension: [ \n"
          + "                                { \n"
          + "                                    url: \"ombCategory\", \n"
          + "                                    valueCoding: { \n"
          + "                                        system: \"http://hl7.org/fhir/v3/Race\", \n"
          + "                                        code: \"2016-3\", \n"
          + "                                        display: \"White\" \n"
          + "                                    } \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    url: \"text\", \n"
          + "                                    valueString: \"White\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", \n"
          + "                            extension: [ \n"
          + "                                { \n"
          + "                                    url: \"ombCategory\", \n"
          + "                                    valueCoding: { \n"
          + "                                        system: \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", \n"
          + "                                        code: \"2186-5\", \n"
          + "                                        display: \"Not Hispanic or Latino\" \n"
          + "                                    } \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    url: \"text\", \n"
          + "                                    valueString: \"Not Hispanic or Latino\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", \n"
          + "                            valueCode: \"M\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    identifier: [ \n"
          + "                        { \n"
          + "                            use: \"usual\", \n"
          + "                            type: { \n"
          + "                                coding: [ \n"
          + "                                    { \n"
          + "                                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                                        code: \"MR\" \n"
          + "                                    } \n"
          + "                                ] \n"
          + "                            }, \n"
          + "                            system: \"http://va.gov/mvi\", \n"
          + "                            value: \"2000163\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            use: \"official\", \n"
          + "                            type: { \n"
          + "                                coding: [ \n"
          + "                                    { \n"
          + "                                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                                        code: \"SB\" \n"
          + "                                    } \n"
          + "                                ] \n"
          + "                            }, \n"
          + "                            system: \"http://hl7.org/fhir/sid/us-ssn\", \n"
          + "                            value: \"999-61-4803\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    name: [ \n"
          + "                        { \n"
          + "                            use: \"usual\", \n"
          + "                            text: \"Mr. Aurelio227 Cruickshank494\", \n"
          + "                            family: [ \n"
          + "                                \"Cruickshank494\" \n"
          + "                            ], \n"
          + "                            given: [ \n"
          + "                                \"Aurelio227\" \n"
          + "                            ] \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    telecom: [ \n"
          + "                        { \n"
          + "                            system: \"phone\", \n"
          + "                            value: \"5555191065\", \n"
          + "                            use: \"mobile\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            system: \"email\", \n"
          + "                            value: \"Aurelio227.Cruickshank494@email.example\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    gender: \"male\", \n"
          + "                    birthDate: \"1995-02-06\", \n"
          + "                    deceasedBoolean: \"false\", \n"
          + "                    address: [ \n"
          + "                        { \n"
          + "                            line: [ \n"
          + "                                \"909 Rohan Highlands\" \n"
          + "                            ], \n"
          + "                            city: \"Mesa\", \n"
          + "                            state: \"Arizona\", \n"
          + "                            postalCode: \"85120\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    maritalStatus: { \n"
          + "                        coding: [ \n"
          + "                            { \n"
          + "                                system: \"http://hl7.org/fhir/v3/NullFlavor\", \n"
          + "                                code: \"UNK\", \n"
          + "                                display: \"unknown\" \n"
          + "                            } \n"
          + "                        ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
  static final String PATIENT =
      "{ \n"
          + "    id: \"2000163\", \n"
          + "    resourceType: \"Patient\", \n"
          + "    extension: [ \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-race\", \n"
          + "            extension: [ \n"
          + "                { \n"
          + "                    url: \"ombCategory\", \n"
          + "                    valueCoding: { \n"
          + "                        system: \"http://hl7.org/fhir/v3/Race\", \n"
          + "                        code: \"2016-3\", \n"
          + "                        display: \"White\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                { \n"
          + "                    url: \"text\", \n"
          + "                    valueString: \"White\" \n"
          + "                } \n"
          + "            ] \n"
          + "        }, \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-ethnicity\", \n"
          + "            extension: [ \n"
          + "                { \n"
          + "                    url: \"ombCategory\", \n"
          + "                    valueCoding: { \n"
          + "                        system: \"http://hl7.org/fhir/ValueSet/v3-Ethnicity\", \n"
          + "                        code: \"2186-5\", \n"
          + "                        display: \"Not Hispanic or Latino\" \n"
          + "                    } \n"
          + "                }, \n"
          + "                { \n"
          + "                    url: \"text\", \n"
          + "                    valueString: \"Not Hispanic or Latino\" \n"
          + "                } \n"
          + "            ] \n"
          + "        }, \n"
          + "        { \n"
          + "            url: \"http://fhir.org/guides/argonaut/StructureDefinition/argo-birthsex\", \n"
          + "            valueCode: \"M\" \n"
          + "        } \n"
          + "    ], \n"
          + "    identifier: [ \n"
          + "        { \n"
          + "            use: \"usual\", \n"
          + "            type: { \n"
          + "                coding: [ \n"
          + "                    { \n"
          + "                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                        code: \"MR\" \n"
          + "                    } \n"
          + "                ] \n"
          + "            }, \n"
          + "            system: \"http://va.gov/mvi\", \n"
          + "            value: \"2000163\" \n"
          + "        }, \n"
          + "        { \n"
          + "            use: \"official\", \n"
          + "            type: { \n"
          + "                coding: [ \n"
          + "                    { \n"
          + "                        system: \"http://hl7.org/fhir/v2/0203\", \n"
          + "                        code: \"SB\" \n"
          + "                    } \n"
          + "                ] \n"
          + "            }, \n"
          + "            system: \"http://hl7.org/fhir/sid/us-ssn\", \n"
          + "            value: \"999-61-4803\" \n"
          + "        } \n"
          + "    ], \n"
          + "    name: [ \n"
          + "        { \n"
          + "            use: \"usual\", \n"
          + "            text: \"Mr. Aurelio227 Cruickshank494\", \n"
          + "            family: [ \n"
          + "                \"Cruickshank494\" \n"
          + "            ], \n"
          + "            given: [ \n"
          + "                \"Aurelio227\" \n"
          + "            ] \n"
          + "        } \n"
          + "    ], \n"
          + "    telecom: [ \n"
          + "        { \n"
          + "            system: \"phone\", \n"
          + "            value: \"5555191065\", \n"
          + "            use: \"mobile\" \n"
          + "        }, \n"
          + "        { \n"
          + "            system: \"email\", \n"
          + "            value: \"Aurelio227.Cruickshank494@email.example\" \n"
          + "        } \n"
          + "    ], \n"
          + "    gender: \"male\", \n"
          + "    birthDate: \"1995-02-06\", \n"
          + "    deceasedBoolean: \"false\", \n"
          + "    address: [ \n"
          + "        { \n"
          + "            line: [ \n"
          + "                \"909 Rohan Highlands\" \n"
          + "            ], \n"
          + "            city: \"Mesa\", \n"
          + "            state: \"Arizona\", \n"
          + "            postalCode: \"85120\" \n"
          + "        } \n"
          + "    ], \n"
          + "    maritalStatus: { \n"
          + "        coding: [ \n"
          + "            { \n"
          + "                system: \"http://hl7.org/fhir/v3/NullFlavor\", \n"
          + "                code: \"UNK\", \n"
          + "                display: \"unknown\" \n"
          + "            } \n"
          + "        ] \n"
          + "    } \n"
          + "} \n";

  static final String PRACTITIONER =
      "{ \n"
          + "    resourceType: \"Practitioner\", \n"
          + "    id: \"9e8531cb-8069-5328-b737-938fa044a4e2\", \n"
          + "    active: \"true\", \n"
          + "    name: { \n"
          + "        use: \"usual\", \n"
          + "        text: \"CARUNGIN,CHAD REY V\", \n"
          + "        family: [ \n"
          + "            \"CARUNGIN\" \n"
          + "        ], \n"
          + "        given: [ \n"
          + "            \"CHAD REY\" \n"
          + "        ], \n"
          + "        suffix: [ \n"
          + "            \"V\" \n"
          + "        ] \n"
          + "    }, \n"
          + "    telecom: [ \n"
          + "        { \n"
          + "            system: \"phone\", \n"
          + "            value: \"318-8387\", \n"
          + "            use: \"work\" \n"
          + "        }, \n"
          + "        { \n"
          + "            system: \"phone\", \n"
          + "            value: \"638334566\", \n"
          + "            use: \"home\" \n"
          + "        } \n"
          + "    ], \n"
          + "    gender: \"male\", \n"
          + "    birthDate: \"1964-02-16\", \n"
          + "    practitionerRole: [ \n"
          + "        { \n"
          + "            managingOrganization: { \n"
          + "                reference: \"https://api.va.gov/services/argonaut/v0/Organization/a29c7d77-fbae-5852-a905-1b18385b0339\", \n"
          + "                display: \"MANILA-RO\" \n"
          + "            }, \n"
          + "            role: { \n"
          + "                coding: [ \n"
          + "                    { \n"
          + "                        system: \"http://hl7.org/fhir/practitioner-role\", \n"
          + "                        code: \"doctor\", \n"
          + "                        display: \"Doctor\" \n"
          + "                    } \n"
          + "                ] \n"
          + "            }, \n"
          + "            location: [ \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/fb2a6389-0512-5ed1-9b49-811d5f3fdf3d\", \n"
          + "                    display: \"PULMO CONSULT\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/be4abb7c-87ea-57de-9347-df849897ea28\", \n"
          + "                    display: \"ZZORANGE\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/c7c5e616-4304-5956-804f-36038889f712\", \n"
          + "                    display: \"ZZZ MAN PACT ORANGE\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/2a560bee-9f00-5758-aaa3-21c0f929a7f6\", \n"
          + "                    display: \"ZZORANGE INTERNAL MED CLINIC\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/ada6bbf5-f121-582e-b832-13387fe4feff\", \n"
          + "                    display: \"MAN PACT WALK-IN\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: \"https://api.va.gov/services/argonaut/v0/Location/d05e1bc2-9527-51e9-bc35-0132f2af3c53\", \n"
          + "                    display: \"E-CONSULT PULMO\" \n"
          + "                }, \n"
          + "                { \n"
          + "                    reference: https://api.va.gov/services/argonaut/v0/Location/1cdb2958-e0fb-5711-8907-d582662e1be7, \n"
          + "                    display: MNL-SECMSG-PULMO \n"
          + "                } \n"
          + "            ], \n"
          + "            healthcareService: [ \n"
          + "                { \n"
          + "                    display: \"PROFESSIONAL SERVICES DIVISION\" \n"
          + "                } \n"
          + "            ] \n"
          + "        } \n"
          + "    ] \n"
          + "} ";

  static final String PRACTITIONER_BUNDLE =
      "{ \n"
          + "    resourceType: \"Bundle\", \n"
          + "    type: \"searchset\", \n"
          + "    total: 1, \n"
          + "    link: [ \n"
          + "        { \n"
          + "            relation: \"self\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: \"first\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        }, \n"
          + "        { \n"
          + "            relation: last\", \n"
          + "            url: \"https://dev-api.va.gov/services/argonaut/v0/Practitioner?patient=1017283148V813263&page=1&_count=15\" \n"
          + "        } \n"
          + "    ], \n"
          + "    entry: [ \n"
          + "        { \n"
          + "            fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/9e8531cb-8069-5328-b737-938fa044a4e2\", \n"
          + "            resource: { \n"
          + "                fullUrl: \"https://dev-api.va.gov/services/argonaut/v0/Practitioner/9e8531cb-8069-5328-b737-938fa044a4e2\", \n"
          + "                resource: { \n"
          + "                    resourceType: \"Practitioner\", \n"
          + "                    id: \"9e8531cb-8069-5328-b737-938fa044a4e2\", \n"
          + "                    active: \"true\", \n"
          + "                    name: { \n"
          + "                        use: \"usual\", \n"
          + "                        text: \"CARUNGIN,CHAD REY V\", \n"
          + "                        family: [ \n"
          + "                            \"CARUNGIN\" \n"
          + "                        ], \n"
          + "                        given: [ \n"
          + "                            \"CHAD REY\" \n"
          + "                        ], \n"
          + "                        suffix: [ \n"
          + "                            \"V\" \n"
          + "                        ] \n"
          + "                    }, \n"
          + "                    telecom: [ \n"
          + "                        { \n"
          + "                            system: \"phone\", \n"
          + "                            value: \"318-8387\", \n"
          + "                            use: \"work\" \n"
          + "                        }, \n"
          + "                        { \n"
          + "                            system: \"phone\", \n"
          + "                            value: \"638334566\", \n"
          + "                            use: \"home\" \n"
          + "                        } \n"
          + "                    ], \n"
          + "                    gender: \"male\", \n"
          + "                    birthDate: \"1964-02-16\", \n"
          + "                    practitionerRole: [ \n"
          + "                        { \n"
          + "                            managingOrganization: { \n"
          + "                                reference: \"https://api.va.gov/services/argonaut/v0/Organization/a29c7d77-fbae-5852-a905-1b18385b0339\", \n"
          + "                                display: \"MANILA-RO\" \n"
          + "                            }, \n"
          + "                            role: { \n"
          + "                                coding: [ \n"
          + "                                    { \n"
          + "                                        system: \"http://hl7.org/fhir/practitioner-role\", \n"
          + "                                        code: \"doctor\", \n"
          + "                                        display: \"Doctor\" \n"
          + "                                    } \n"
          + "                                ] \n"
          + "                            }, \n"
          + "                            location: [ \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/fb2a6389-0512-5ed1-9b49-811d5f3fdf3d\", \n"
          + "                                    display: \"PULMO CONSULT\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/be4abb7c-87ea-57de-9347-df849897ea28\", \n"
          + "                                    display: \"ZZORANGE\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/c7c5e616-4304-5956-804f-36038889f712\", \n"
          + "                                    display: \"ZZZ MAN PACT ORANGE\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/2a560bee-9f00-5758-aaa3-21c0f929a7f6\", \n"
          + "                                    display: \"ZZORANGE INTERNAL MED CLINIC\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/ada6bbf5-f121-582e-b832-13387fe4feff\", \n"
          + "                                    display: \"MAN PACT WALK-IN\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: \"https://api.va.gov/services/argonaut/v0/Location/d05e1bc2-9527-51e9-bc35-0132f2af3c53\", \n"
          + "                                    display: \"E-CONSULT PULMO\" \n"
          + "                                }, \n"
          + "                                { \n"
          + "                                    reference: https://api.va.gov/services/argonaut/v0/Location/1cdb2958-e0fb-5711-8907-d582662e1be7, \n"
          + "                                   display: MNL-SECMSG-PULMO \n"
          + "                                } \n"
          + "                            ], \n"
          + "                            healthcareService: [ \n"
          + "                                { \n"
          + "                                    display: \"PROFESSIONAL SERVICES DIVISION\" \n"
          + "                                } \n"
          + "                            ] \n"
          + "                        } \n"
          + "                    ] \n"
          + "                }, \n"
          + "                search: { \n"
          + "                    mode: \"match\" \n"
          + "                } \n"
          + "        } \n"
          + "    ] \n"
          + "} ";
}
