@startuml

skinparam handwritten true
skinparam monochrome true
left to right direction

actor consumer
database "cdw"
database "id-store" as iddb
rectangle "data-query"
rectangle "ids"
rectangle "mr-anderson" as mra

consumer -(0- data-query
data-query -(0- mra
mra -- cdw
mra -(0- ids
ids -- iddb

@enduml
